### ISSUE TITLE
Can this be used in Expo?

### ISSUE THREAD

**Issue by Messi10AP** [RobinBobin/react-native-google-drive-api-wrapper#11]
I saw that it needs to link a library, but expo doesn't allow that. Is there any way to use it without having to export?

**Comment by Messi10AP** [comment]
so if i were just using the .get function, would I need to use `react-native-fs`?

**Comment by RobinBobin** [comment]
Nope.

**Comment by Messi10AP** [comment]
perfect, thanks!

**Comment by RobinBobin** [comment]
Glad my package suits your needs.

You're welcome.


>Понедельник, 15 апреля 2019, 23:28 +03:00 от Abhishek Patel <notifications@github.com>:
>
>perfect, thanks!
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
� убен Шалимов

**Comment by ksrudeboy** [comment]
Expo has its own fs module. Will it work with that or it specifically needs react-native-fs??

**Comment by RobinBobin** [comment]
`Files.js` imports `RNFS` from `react-native-fs` and then invokes `downloadFile()` on it. Thus, everything will work, if you change the import statement and the module you currently have supports the same functionality.
