### ISSUE TITLE
Files.get not working properly

### ISSUE THREAD

**Issue by gayanMadurapperuma** [RobinBobin/react-native-google-drive-api-wrapper#14]
Can't get plain/text file content.
Source code given below
`GDrive.setAccessToken(this.props.userGoogleAuthInfo.accessToken);
 GDrive.init();
 GDrive.isInitialized() ? console.log('Gdrive initialized') : console.log('Gdrive not initialized');
 GDrive.files.get(fileId, {alt: "media"}).then(res => {
          console.log(res);
  }).catch(e => {
          console.log(e);   
  })`

response was
`headers: Headers {map: {…}}
ok: true
status: 200
statusText: undefined
type: "default"
url: "https://www.googleapis.com/drive/v3/files/1M5aPXRDrREF5zQaoq28m1alW4BgPIREH?alt=media"
_bodyBlob: Blob
_data:
blobId: "9247a753-52ff-4d33-9139-64aa582ba468"
offset: 0
size: 53376
__proto__: Object
data: (...)
size: (...)
type: (...)
__proto__: Object
_bodyInit: Blob {_data: {…}}`

I don't have any idea. my another testing project working fine. is it google project setup issue or something?.

**Comment by gayanMadurapperuma** [comment]
I changed React-native version 0.59.8 to 0.58.3. Then working fine. please check for a latest version.
`headers: Headers
map:
alt-svc: "quic=":443"; ma=2592000; v="46,44,43,39""
cache-control: "private, max-age=0, must-revalidate"
content-disposition: "attachment"
content-type: "plain/text"
date: "Thu, 30 May 2019 21:44:47 GMT"
expires: "Thu, 30 May 2019 21:44:47 GMT"
server: "UploadServer"
vary: "X-Origin"
warning: "214 UploadServer gzipped"
x-guploader-uploadid: "AEnB2UoMjLQiVfbJ74kM6yrJT6_M9nYT-MvZHNKOfDeOac1glqelgwUkJNpEzP7CTeMBcC9-w0xLjp48S9N_O_KcWeqNn2pl0A"
__proto__: Object
__proto__: Object
ok: true
status: 200
statusText: undefined
type: "default"
url: "https://www.googleapis.com/drive/v3/files/1M5aPXRDrREF5zQaoq28m1alW4BgPIREH?alt=media"
_bodyInit: "U2FsdGVkX1+WKO9GW14qKP0LeyJotWz8ljPzbpbDABd8RvI+G...`

**Comment by wmonecke** [comment]
Hi! I also updated RN to latest 0.59 and have this issue. Any ideas on how to resolve it? :)

**Comment by RobinBobin** [comment]
Hi everyone!

Sorry for the inconvenience. I'll look into it in a couple of days. Unfortunately I don't have much spare time right now.


>Пятница, 31 мая 2019, 12:48 +03:00 от Walter Monecke <notifications@github.com>:
>
>Hi! I also updated RN to latest 0.59 and have this issue. Any ideas on how to resolve it? :)
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
� убен Шалимов

**Comment by gayanMadurapperuma** [comment]
@RobinBobin  Thanks. :)

**Comment by RobinBobin** [comment]
Hi everybody!

Sorry it took so long to answer.

I've just checked and I can say I get plain txt file contents just fine.

"react": "16.8.3",
"react-native": "0.59.9",
"react-native-google-drive-api-wrapper": "^1.2.0",
"react-native-google-signin": "^2.0.0"

Are you still facing the problem? If so, please update to the latest versions and try again.

Don't hesitate to write to me if the problem persists.

**Comment by gayanMadurapperuma** [comment]
@RobinBobin I also chacked with same dependency versions of your. but already got same issue.

**Comment by RobinBobin** [comment]
1) In your original post you wrote:

`GDrive.setAccessToken(this.props.userGoogleAuthInfo.accessToken); GDrive.init(); GDrive.isInitialized() ? console.log('Gdrive initialized') : console.log('Gdrive not initialized'); GDrive.files.get(fileId, {alt: "media"}).then(res => { console.log(res); }).catch(e => { console.log(e); })`

`GDrive.files.get()` returns the result of `fetch()`, so you have to call `text()` or `json()` to get the actual file content. `ok: true status: 200` tells you everything's fine.

2) The API for `react-native-google-signin` changed slightly as for getting an access token. Are you sure you updated your code?

**Comment by gayanMadurapperuma** [comment]
@RobinBobin Yes, it gave status code 200. But before I told you when I implemented react-native@0.58.3 it was return _bodyBlob as a plain text of my file content. But now _bodyBlob return Blob value. It wasn't return my file content.

**Comment by gayanMadurapperuma** [comment]
@RobinBobin I tried to execute same request using axios. It was worked fine in react-native latest version.

**Comment by RobinBobin** [comment]
I've never used `axios`, so I can tell nothing about it.

As for `fetch()`, I've always used `text()` or `json()` after it.

**Comment by wmonecke** [comment]
I also had an issue and thought it was your package however I was calling JSON.stringify() and that stopped working somehow and now I changed it to .json() and now it works fine. 

@RobinBobin thanks for your time! 
@gayanMadurapperuma here is my code that is working. Try it and maybe see if it works for you too :)

```
return GDrive.files.get(fileId, { alt: 'media' })
        .then(res => {
          res.json().then(data => {
            // access your data here
          })
        })
```

**Comment by RobinBobin** [comment]
Here's an excerpt from my app, written to test the case. This code is run from `componentDidMount()`.

      GDrive.init();
      
      await GoogleSignin.configure({
         scopes: [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appfolder"
         ],
      });
      
      try {
         await GoogleSignin.signIn();
         console.log("Signed in.");
                  
         GDrive.setAccessToken((await GoogleSignin.getTokens()).accessToken);
         
         try {
            console.log(await (await GDrive.files.get(await GDrive.files.getId("1.txt", ["root"]), {alt: "media"})).text());
         } catch (e) {
            console.log(e);
         }
         
         await GoogleSignin.signOut();
         console.log("Signed out.");
      } catch (e) {
         console.log(e);
      }
   }

It outputs the contents of a text file.

**Comment by RobinBobin** [comment]
@wmonecke You're welcome.

**Comment by sagarkpatil3** [comment]
@RobinBobin Thanks a lot it worked for me.
