### ISSUE TITLE
I not getting the list of files response when i use list() method. 

### ISSUE THREAD

**Issue by sagarkpatil3** [RobinBobin/react-native-google-drive-api-wrapper#17]
response is success but it is not showing any list of files.
`let files = await  GDrive.files.list({
      "corpus": "user",
      "includeItemsFromAllDrives": true,
      "includeTeamDriveItems": true,
      "supportsAllDrives": true,
      "supportsTeamDrives": true
    });
    console.log("files",files)`

**Response** -> {headers: Headers
map: {alt-svc: "quic=":443"; ma=2592000; v="46,43",h3-Q049=":443";…046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000", server: "GSE", x-xss-protection: "1; mode=block", x-frame-options: "SAMEORIGIN", x-content-type-options: "nosniff", …}
__proto__: Object
ok: true
status: 200
statusText: undefined
type: "default"
url: "https://www.googleapis.com/drive/v3/files?corpus=user&includeItemsFromAllDrives=true&includeTeamDriveItems=true&supportsAllDrives=true&supportsTeamDrives=true"
_bodyBlob: Blob {_data: {…}}
_bodyInit: Blob {_data: {…}}
}

**Comment by mi5ha** [comment]
@sagarkpatil3 What was the issue? I have the same problem

**Comment by MehdiRaza1998** [comment]
What was the solution, I am also not able to get the list.

**Comment by sagarkpatil3** [comment]
> What was the solution, I am also not able to get the list.

try response.json();

**Comment by ambessh** [comment]
> response is success but it is not showing any list of files.
> `let files = await GDrive.files.list({ "corpus": "user", "includeItemsFromAllDrives": true, "includeTeamDriveItems": true, "supportsAllDrives": true, "supportsTeamDrives": true }); console.log("files",files)`
> 
> **Response** -> {headers: Headers
> map: {alt-svc: "quic=":443"; ma=2592000; v="46,43",h3-Q049=":443";…046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000", server: "GSE", x-xss-protection: "1; mode=block", x-frame-options: "SAMEORIGIN", x-content-type-options: "nosniff", …}
> **proto**: Object
> ok: true
> status: 200
> statusText: undefined
> type: "default"
> url: "https://www.googleapis.com/drive/v3/files?corpus=user&includeItemsFromAllDrives=true&includeTeamDriveItems=true&supportsAllDrives=true&supportsTeamDrives=true"
> _bodyBlob: Blob {_data: {…}}
> _bodyInit: Blob {_data: {…}}
> }

 GDrive.files.list({spaces:'appDataFolder'}).then(res=>{
                              console.log(res.json())
                            })
