### ISSUE TITLE
Question: is there a way to receive modifiedTime directly via createFileMultipart

### ISSUE THREAD

**Issue by tststs** [RobinBobin/react-native-google-drive-api-wrapper#18]
Hey,

i wonder if its possible to receive modifiedTime directly as a result when creating a file via createFileMultipart?

Currently i create the file then get modifiedTime with `GDrive.files.get(adapterId, {fields: 'modifiedTime'})` which means two API calls.

I've seen that there is a `date` field in the response header for `createFileMultipart`:

`"date": "Thu, 14 Nov 2019 11:38:19 GMT"` but i don't know if this is always the same as modifiedTime.

I also haven't found anything in the docs from google so i thought i might ask the question here. :)

Thanks in advance!

**Comment by RobinBobin** [comment]
Hi, there!

I would be glad to help you out, but I'm afraid I have no further info. How about creating several files in a row, waiting for several seconds in between, and then checking the `date` field and comparing it to your local time? Maybe it might give you a hint.
