### ISSUE TITLE
GDrive.files.get does not work

### ISSUE THREAD

**Issue by ryuheimat** [RobinBobin/react-native-google-drive-api-wrapper#2]
I can get fileId using `getId()` function, but cannot get contents of file.
Download file is necessary?
Here is my code.
```
if (GDrive.isInitialized()) {
  try {
    let fileId = await GDrive.files.getId('File', ['root'], 'text/plain')
    let content = await GDrive.files.get(fileId)
  } catch(e) {
    console.log(e)
  }
}
```

By the way, Upload with GDrive is working.

**Comment by RobinBobin** [comment]
Hi there!

It looks like you got it working. If something is unclear, please don't hesitate to contact me.

**Comment by ryuheimat** [comment]
Hi @RobinBobin 
I can get something with `get()` function, but not contents of file.
I can get only kind, id, name and mimeType even though the file is text/html

How can I get contents?
Thanks.

**Comment by RobinBobin** [comment]
Hi!

Give me some time please. I'll write a tiny app to test the case.


>Пятница, 24 августа 2018, 19:53 +03:00 от Ryuhei Matsuda <notifications@github.com>:
>
>Hi  @RobinBobin
>I can get something with get() function, but not contents of file.
>I can get only kind, id, name and mimeType even though the file is text/html
>How can I get contents?
>Thanks.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Рубен Шалимов

**Comment by RobinBobin** [comment]
Still checking.
Are you sure it is NOT a Google Document file? For them `export()` has to be used.

**Comment by ryuheimat** [comment]
I create file on google drive by this.
```
GDrive.files.createFileMultipart("my file content", "text/plain", {
          parents: ['root'],
          name: "file"
        })
```

**Comment by ryuheimat** [comment]
Fixed?

**Comment by RobinBobin** [comment]
Please add `alt: "media"` to the last param of `get()`.
   ```
GDrive.files.get(fileId, {
      alt: "media"
   })
```
I'll change the docs.

**Comment by ryuheimat** [comment]
Thanks. it works.

**Comment by RobinBobin** [comment]
You're welcome.


>Суббота, 25 августа 2018, 1:52 +03:00 от Ryuhei Matsuda <notifications@github.com>:
>
>Thanks. it works.
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Рубен Шалимов

**Comment by Yajan** [comment]
How to get meta data using get ?

**Comment by RobinBobin** [comment]
get()

Gets a file's metadata or a text-file's content by ID. By default the metadata is returned. Use download() for binary files. For queryParams see "Optional query parameters" here. If you want the content of a text-file and not its metadata add alt: "media" to queryParams.

So just don't add `alt: "media"` to `queryParams`.
