### ISSUE TITLE
How to properly set 'parents' property?

### ISSUE THREAD

**Issue by wmonecke** [RobinBobin/react-native-google-drive-api-wrapper#20]
Hi!

Amazing package and so useful, thanks for that!
I am creating a folder called _Moodflow_. Then saving a file inside of it with `.createFileMultipart()`.
However, I am not sure how to set the `parents` property since it is an array.
Should it be `['root/Moodflow']` or `['root', 'Moodflow']`?

Thanks in advance!

Nevermind found the solution:
1. Get the `folderId` using `.safeCreateFolder()`.
````
const folderId = await GDrive.files.safeCreateFolder({ name: "Moodflow", parents: ["root"] });
````
2. Pass it as an array like so: `['root', folderId]`
````
const createdFile = await GDrive.files.createFileMultipart(
  JSON.stringify(appStateToUpload),
  "application/json",
   { parents: ['root', folderId], name: "Moodflow Backup" }
 );
````

**Comment by RobinBobin** [comment]
Hi!

Thanks, glad my package is useful and you got your question sorted.

**Comment by KondaShivaradhan** [comment]
How are you able to give root and the folder id?
I'm getting this error
Error uploading file 'FB_IMG_1702395829747.jpg': [HttpError: {
  "error": {
    "code": 403,
    "message": "Increasing the number of parents is not allowed",
    "errors": [
      {
        "message": "Increasing the number of parents is not allowed",
        "domain": "global",
        "reason": "cannotAddParent"
      }
    ]
  }
}
]

**Comment by RobinBobin** [comment]
I doubt `root` is necessary. Just give a  folder ID as the only member of the `parents` array.
