### ISSUE TITLE
Dynamic folder create

### ISSUE THREAD

**Issue by Moonubanna** [RobinBobin/react-native-google-drive-api-wrapper#22]
Hello,
How can i make dynamic folder and upload our video images in this folder. please suggest me.

Thanks in advance

**Comment by RobinBobin** [comment]
Hello there!
Sorry for the late response.
I didn't quite get you. What do you mean by "dynamic folder" and what exactly are you trying to do?

**Comment by Moonubanna** [comment]
I resolved thank you RobinBobin really thank you for your kind support

**Comment by RobinBobin** [comment]
You're welcome!
