### ISSUE TITLE
How can i change file permission for sharing file 

### ISSUE THREAD

**Issue by ahmad6242** [RobinBobin/react-native-google-drive-api-wrapper#23]
Like in Google Drive i can share and get a shareable link... 
 i ca get a link over here also, but i want to share the file if it is not shared in my google drive !

**Comment by RobinBobin** [comment]
Sorry, this functionality is absent in my package. I've never needed it, so didn't add it.

**Comment by ahmad6242** [comment]
Right!. Do you have any plans of adding this !

**Comment by RobinBobin** [comment]
Not right now, sorry. If you want to make a pull request - you're welcome!

**Comment by c-info** [comment]
Hello @RobinBobin , any updates for this ?

i want to share uploaded files

**Comment by RobinBobin** [comment]
@c-info 
Is [this](https://github.com/RobinBobin/react-native-google-drive-api-wrapper/blob/master/src/README.md#permissions) what you want? If it's not, please open a ticket describing what you need.
