### ISSUE TITLE
I have problem with GDrive.files.get()

### ISSUE THREAD

**Issue by Ahmed-ab96** [RobinBobin/react-native-google-drive-api-wrapper#25]
Hello, I want to get thumbnail url of PDF file from Google drive, but it doesn't work.
however a few months ago it was work.

```
let queryParams = {
fields : "thumbnailLink",
alt: "media"
}
          GDrive.files.get('1ouH2LojK4Od46peKclyCnOOyILeWkCBz', queryParams)
              .then((res)=>{
                console.log(res.url)
              }).catch((err)=>alert(err))
```

Result 
`"url": "https://www.googleapis.com/drive/v3/files/1I-ocFNkjjCtMcVel2tzVPugClv0TpU8F?fields=thumbnailLink&alt=media"}`

but the url should be like this:
`https://lh3.googleusercontent.com/d/1ouH2LojK4Od46peKclyCnOOyILeWkCBz?authuser=0`

**Comment by RobinBobin** [comment]
Hello!

I've never used this functionality, so unfortunately I can only guess. If you state it worked several months ago, maybe Google API has changed since then?

Are you sure the requested file has a thumbnail (```hasThumbnail``` is ```true```).

**Comment by Ahmed-ab96** [comment]
Thanks for replay, i solved.
