### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by fatihbasol** [RobinBobin/react-native-google-drive-api-wrapper#26]
**Hi everyone.** 

### I got this issue when i want to download a file from drive 

I try it with ExternalDirectoryPath and DocumentDirectoryPath. Both of them i got same error

![ssssss](https://user-images.githubusercontent.com/37217214/80120730-19a32e00-8594-11ea-883e-b991bc405b1e.jpg)

![image](https://user-images.githubusercontent.com/37217214/80119379-4bb39080-8592-11ea-9fcc-a7e26c25c175.png)

### I got this error at console:

![image](https://user-images.githubusercontent.com/37217214/80119574-8b7a7800-8592-11ea-8eee-013bc37ab241.png)

  "dependencies": {
    "firebase": "^7.14.1",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-firebase": "^5.6.0",
    "react-native-fs": "^2.13.2",
    "react-native-google-drive-api-wrapper": "^1.2.0",
    "react-native-google-signin": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.9.0",
    "@babel/runtime": "7.9.2",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },

**Comment by RobinBobin** [comment]
Hi!
1. Authorization is done with `GDrive.setAccessToken`. You don't have to set the `Authorization` header manually.
1. Please have a look at the phrase "... bear in mind that `fromUrl` is set automatically and any user supplied value will be overwritten" in the `GDrive.files.download()` description.
1. I can be missing something but I didn't find a line, stating where you want the downloaded file stored, in your excerpt.
