### ISSUE TITLE
show images from google drive for particular mail

### ISSUE THREAD

**Issue by mohamed-ikram** [RobinBobin/react-native-google-drive-api-wrapper#28]
how to show or get image from drive without knowing file id

**Comment by RobinBobin** [comment]
I guess you can list all the files and get the id of the file you need.

**Comment by mohamed-ikram** [comment]
I need to show images from google drive so which method I can use to show images can u please help me i have tried the list but its response i cant understand

**Comment by mohamed-ikram** [comment]
GDrive.setAccessToken(this.state.authToken);
    GDrive.init();
    GDrive.isInitialized() ? console.log(true) : console.log(false);
    
    
    let list = await GDrive.files.list({
      q: "'root' in parents",
    });
    console.log(list);

this is the response I am getting
{"_bodyBlob": {"_data": {"__collector": [Object], "blobId": "09f6eab8-55d0-4ccc-82c4-aef363abb533", "offset": 0, "size": 249}}, "_bodyInit": {"_data": {"__collector": [Object], "blobId": "09f6eab8-55d0-4ccc-82c4-aef363abb533", "offset": 0, "size": 249}}, "bodyUsed": false, "headers": {"map": {"alt-svc": "h3-27=\":443\"; ma=2592000,h3-25=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"", "cache-control": "private, max-age=0", "content-security-policy": "frame-ancestors 'self'", "content-type": "application/json; charset=UTF-8", "date": "Tue, 30 Jun 2020 12:25:07 GMT", "expires": "Tue, 30 Jun 2020 12:25:07 GMT", "server": "GSE", "vary": "Origin, X-Origin", "www-authenticate": "Bearer realm=\"https://accounts.google.com/\", error=invalid_token", "x-content-type-options": "nosniff", "x-frame-options": "SAMEORIGIN", "x-xss-protection": "1; mode=block"}}, "ok": false, "status": 401, "statusText": undefined, "type": "default", "url": "https://www.googleapis.com/drive/v3/files?q=%27root%27%20in%20parents"}

**Comment by mohamed-ikram** [comment]
let list = await GDrive.files.list({
      q:"type:image",
    });
    console.log(list);
when i pass images in query params response is like this
 {"_bodyBlob": {"_data": {"__collector": [Object], "blobId": "d847725e-e774-47c1-8c8f-ee7f0a982b4b", "offset": 0, "size": 249}}, "_bodyInit": {"_data": {"__collector": [Object], "blobId": "d847725e-e774-47c1-8c8f-ee7f0a982b4b", "offset": 0, "size": 249}}, "bodyUsed": false, "headers": {"map": {"alt-svc": "h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-25=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"", "cache-control": "private, max-age=0", "content-security-policy": "frame-ancestors 'self'", "content-type": "application/json; charset=UTF-8", "date": "Tue, 30 Jun 2020 12:28:48 GMT", "expires": "Tue, 30 Jun 2020 12:28:48 GMT", "server": "GSE", "vary": "Origin, X-Origin", "www-authenticate": "Bearer realm=\"https://accounts.google.com/\", error=invalid_token", "x-content-type-options": "nosniff", "x-frame-options": "SAMEORIGIN", "x-xss-protection": "1; mode=block"}}, "ok": false, "status": 401, "statusText": undefined, "type": "default", "url": "https://www.googleapis.com/drive/v3/files?q=type:image"}

**Comment by RobinBobin** [comment]
The status you're getting (401) is "Unauthorized", as far as I understand. Are you sure your authorization is successful? Can you create a dummy file with `createFileMultipart()` or access google drive in any other way?

**Comment by mohamed-ikram** [comment]
yes the user is authorized i have checked by **GDrive.isInitialized() ? console.log(true) : console.log(false);** i have recieved true in the output thats how iam saying

**Comment by mohamed-ikram** [comment]
i got Id token from google-signin followed by @react-native-community/google-signin 
my function call is
**try {
      await GoogleSignin.hasPlayServices();
      const userInfo = await GoogleSignin.signIn();
      console.log(userInfo);
      this.setState({
        name: userInfo.user.name,
        email: userInfo.user.email,
        photo: userInfo.user.photo,
        authToken: userInfo.idToken,
      });
      // this.setState({userInfo});
    } catch (error) {
      if (error.code === statusCodes.SIGN_IN_CANCELLED) {
        // user cancelled the login flow
      } else if (error.code === statusCodes.IN_PROGRESS) {
        // operation (e.g. sign in) is in progress already
      } else if (error.code === statusCodes.PLAY_SERVICES_NOT_AVAILABLE) {
        // play services not available or outdated
      } else {
        // some other error happened
      }
      console.log(error);
    } // let id = GDrive.files.getId(null, null, "image / jpg", false)
    // console.log(id);
    GDrive.setAccessToken(this.state.authToken);
    GDrive.init();
    GDrive.isInitialized() ? console.log(true) : console.log(false);
    // const contents = 'My text file contents';
    // or
    const contents = [10, 20, 30];
    GDrive.files.createFileMultipart(contents, 'corresponding mime type', {
      parents: ['root'],
      name: 'My file',
    });**

**Comment by RobinBobin** [comment]
`GDrive.isInitialized()` simply tells you if `GDrive.accessToken()` evaluates to `true`. You can set the token to any arbitrary value and this method will return `true`, but that does not mean the user is authorized.

Are you sure the scope you supply to `GoogleSignin.configure()` is correct?

Is the call to `GDrive.files.createFileMultipart()` successful?

**Comment by mohamed-ikram** [comment]
this is my code i have shared the way i call the GDrive.files.createFileMultipart() is correct or not pls help

```
class GoogleSign extends Component {
  state = {
    name: '',
    photo: null,
    email: '',
    authToken: '',
  };

  componentDidMount() {
    GoogleSignin.configure({
      scopes: ['https://www.googleapis.com/auth/drive.readonly'], // what API you want to access on behalf of the user, default is email and profile
      webClientId:
        '374305874300-gpg81ee2gv54thfu9ctfdeergk4094v4.apps.googleusercontent.com', // client ID of type WEB for your server (needed to verify user ID and offline access)
      offlineAccess: true, // if you want to access Google API on behalf of the user FROM YOUR SERVER
      forceCodeForRefreshToken: true, // [Android] related to `serverAuthCode`, read the docs link below `*.`
    });
  }
  _signIn = async () => {
    try {
      await GoogleSignin.hasPlayServices();
      const userInfo = await GoogleSignin.signIn();
      const token = await GoogleSignin.getTokens();
      console.log(token.accessToken);

      // console.log(userInfo);
      this.setState({
        name: userInfo.user.name,
        email: userInfo.user.email,
        photo: userInfo.user.photo,
        authToken: token.accessToken,
      });
    } catch (error) {
      if (error.code === statusCodes.SIGN_IN_CANCELLED) {
        // user cancelled the login flow
      } else if (error.code === statusCodes.IN_PROGRESS) {
        // operation (e.g. sign in) is in progress already
      } else if (error.code === statusCodes.PLAY_SERVICES_NOT_AVAILABLE) {
        // play services not available or outdated
      } else {
        // some other error happened
      }
      console.log(error);
    }

    console.log(this.state.authToken);
    GDrive.setAccessToken(this.state.authToken);
    GDrive.init();
    GDrive.isInitialized() ? console.log(true) : console.log(false);
    const contents = 'My text file contents';

    **GDrive.files.createFileMultipart(contents, 'corresponding mime type', {
      parents: ['root'],
      name: 'My file',
    });**
    let list = await GDrive.files.list({
      q: 'type:image',
    });
    console.log(list);
  };
  render() {
    return (
      <View>
        <Text>GoogleSignIn</Text>
        <GoogleSigninButton
          style={{width: 192, height: 48}}
          size={GoogleSigninButton.Size.Wide}
          color={GoogleSigninButton.Color.Light}
          onPress={this._signIn}
        />
        <Text>{this.state.name}</Text>
        <Text>{this.state.email}</Text>
        <Image
          source={{uri: this.state.photo}}
          style={{width: 100, height: 100}}
        />
      </View>
    );
  }
}
```

**Comment by mohamed-ikram** [comment]
what params do i need to send to get list of images

` let list = await GDrive.files.list({
      q: 'type:image',
    });
    console.log(list);`

**Comment by RobinBobin** [comment]
Is the call to GDrive.files.createFileMultipart() successful?

As for the params, did you have a look at [the docs](https://developers.google.com/drive/api/v3/reference/files/list)?

**Comment by mohamed-ikram** [comment]
no the call to GDrive.files.createFileMultipart() is unsuccessful

**Comment by RobinBobin** [comment]
You request read-only access.
scopes: ['https://www.googleapis.com/auth/drive.readonly']

**Comment by mohamed-ikram** [comment]
okay thanks for ur help

**Comment by RobinBobin** [comment]
You're welcome. Another hint. Try setting the widest scope, allowing all kinds of access to everything.
