### ISSUE TITLE
"Delivery Status Notification(Failure)" email with permissions create

### ISSUE THREAD

**Issue by ankitwandx** [RobinBobin/react-native-google-drive-api-wrapper#30]
This is how I am sharing a file:

`GDrive.permissions.create(
    FILE_ID,
    {
      role: "reader",
      type: "user",
      emailAddress: SOME_EMAIL_ADDRESS
    }
);`

But I keep getting this **Delivery Status Notification(Failure)** email. The file is, however, successfully shared. 

How do I stop getting these emails? I do not want any failure acknowledgment email. My requirement is that even if the sharing fails, I should not receive any such email.

![WhatsApp Image 2020-07-01 at 8 56 02 PM](https://user-images.githubusercontent.com/43344545/86279145-2f1d7f80-bbf7-11ea-9fd6-433f92521365.jpeg)

**Comment by RobinBobin** [comment]
Who's sending these emails to you?

**Comment by ankitwandx** [comment]
Hi Robin,

When I create permission to share a file to any email address, I get the said email from `Mail Delivery Subsystem <mailer-daemon@googlemail.com>` and it is sent to `3lZP8XgkJAKwhUO.MZWUfSYMUX.OaY@doclist.bounces.google.com`.

However, I think I have resolved it by forking this library and adding this line in permissions.js `return fetch(`${GDrive._urlFiles}/${fileId}${permissions}?sendNotificationEmail=false`, {`

**Comment by RobinBobin** [comment]
I'm glad you sorted it out.

**Comment by mi5ha** [comment]
@RobinBobin  I have created [PR](https://github.com/RobinBobin/react-native-google-drive-api-wrapper/pull/31) that would solve this issue with sendNotificationEmail, and would also let you add other query params  besides sendNotificationEmail
