### ISSUE TITLE
GDrive.files.getId() Error

### ISSUE THREAD

**Issue by dinesh14ahuja** [RobinBobin/react-native-google-drive-api-wrapper#33]
Hello,
As per https://www.npmjs.com/package/react-native-google-drive-api-wrapper document 
 ```
GDrive.files.getId(
     name: String, // The name.
     parents: [String], // The parents.
     mimeType: String, // The mime type.
     trashed: Boolean // Whether the file is trashed. Default: false
 );
```
I used this function as 
```
GDrive.files.getId(fileName, false )
     .promise.then((r)=>{
         console.log(r);
     });
```
But it is showing error 
` The type cast expression is expected to be wrapped with parenthesis (60:9)

  58 | getFileId(fileName){
  59 |     GDrive.files.getId(
> 60 |      name: fileName,
     |          ^
  61 |      trashed: false )
  62 |      .promise.then((r)=>{
  63 |          console.log(r);`

Someone Kindly help me , Thanks in advance

**Comment by RobinBobin** [comment]
You're passing `false` (a boolean value) as the second argument, while it must be an array of strings.

**Comment by dinesh14ahuja** [comment]
But even when I pass GDrive.files.get(name:fileName,trashed:false) , It is giving error 
`` The type cast expression is expected to be wrapped with parenthesis (60:9)

58 | getFileId(fileName){
59 | GDrive.files.getId(

60 | name: fileName,
| ^
61 | trashed: false )
62 | .promise.then((r)=>{
63 | console.log(r);``

**Comment by dinesh14ahuja** [comment]
name: String, // The name.
    parents: [String], // The parents.
    mimeType: String, // The mime type.
    trashed: Boolean // Whether the file is trashed. Default: false
And are parents and mimeType keys mandatory?

Can you share a sample of this function , It would help me alot.Thanks

**Comment by RobinBobin** [comment]
I'm afraid I don't have a working example at hand. Looking at the source code I can suppose `mimeType` is optional and `parents` is mandatory.
