### ISSUE TITLE
GDrive wrapper stopped working

### ISSUE THREAD

**Issue by wmonecke** [RobinBobin/react-native-google-drive-api-wrapper#34]
Hi there!

I have been using this library for a couple of months now and it worked GREAT! Recently, some users have reported that the backup feature of my app stopped working and I just confirmed this, and I can’t find the source of the issue.

I have an upload/download-app-data functions (posted below) and it seems that both are not working correctly.

The `createNewGoogleDriveBackup` function DOES create a folder and it appears that `GDrive.files.createFileMultipart` successfully finishes (aka uploads the file) but when I go to my Drive I can only see that the folder was created but it is empty.

When I try to download the file it is unable to find the file within.

Any hints would be greatly appreciated! 
This code worked untouched for the past 5 months or so, and I haven’t touched it since.
 
------

EDIT: After a bit of digging I see that `GDrive.files.createFileMultipart` is resolving with status `403` (Forbidden). So I am allowed to create a folder but not allowed to upload a file, which I find strange.

When I log in with Google I specifically request permission in the scopes as seen below:

`````
GoogleSignin.configure({
      scopes: ['https://www.googleapis.com/auth/drive.file'], // what API you want to access on behalf of the user
      webClientId: '...', // client ID of type WEB for your server (needed to verify user ID and offline access)
      offlineAccess: true, // if you want to access Google API on behalf of the user FROM YOUR SERVER
      forceConsentPrompt: false, // [Android] if you want to show the authorization prompt at each login.
    });
``````

------
# createNewGoogleDriveBackup
`````
const BACKUP_FOLDER_NAME = 'Moodflow';
const BACKUP_FILE_NAME = 'moodflow_backup.json';

export const createNewGoogleDriveBackup = (shouldUpdateRequestMetadata = false) => {
  return async dispatch => {
    const appState = store.getState()

    shouldUpdateRequestMetadata ? dispatch({ type: START_REQUEST }) : null;
    try {
      await GoogleSignin.signInSilently()
      const token = await GoogleSignin.getTokens();
      GDrive.setAccessToken(token.accessToken);
      GDrive.init();

      // Gets the id of the first folder with the specified name and parents, creating the folder if it doesn't exist. 
      const folderId = await GDrive.files.safeCreateFolder({ name: BACKUP_FOLDER_NAME, parents: ["root"] });
      console.log('folderId', folderId)
      
      // Gets the id of the first file with the specified metadata. 
      const fileId = await GDrive.files.getId(BACKUP_FILE_NAME, ['root', folderId], "application/json", false);
      console.log('fileId', fileId)

      if (typeof fileId !== 'undefined') {
        await GDrive.files.delete(fileId);
      }

      // modify app state to include only relevant data
      const { challenges, moods, userInfo, routines, activities, gratitudeJournal } = appState;

      const appStateToUpload = {
        moods,
        routines,
        userInfo,
        activities,
        challenges,
        gratitudeJournal,
      };

      const uploadPayload = JSON.stringify(appStateToUpload)
      console.log('uploadPayload', typeof uploadPayload, uploadPayload)

      await GDrive.files.createFileMultipart(
        uploadPayload,
        "application/json",
        { parents: ['root', folderId], name: BACKUP_FILE_NAME },
        false,
      );

      console.log('Uploaded backup!')

      shouldUpdateRequestMetadata ? dispatch({ type: REQUEST_SUCCESSFUL }) : null
      return dispatch({ type: UPDATE_BACKUP_TIMESTAMP });

    } catch (error) {
      console.log('Error creating backup: ', error)
      bugsnag.notify(error)
      return shouldUpdateRequestMetadata ? dispatch({ type: REQUEST_FAILED }) : null
    }
  }
}
`````

# downloadGoogleDriveBackup
`````
export const downloadGoogleDriveBackup = () => {
  return async dispatch => {
    dispatch({ type: START_REQUEST });

    try {
      await GoogleSignin.signInSilently()
      const token = await GoogleSignin.getTokens();
      console.log('token', token)
      GDrive.setAccessToken(token.accessToken);
      GDrive.init();

      // Gets the id of the first folder with the specified name and parents, creating the folder if it doesn't exist. 
      const folderId = await GDrive.files.safeCreateFolder({ name: BACKUP_FOLDER_NAME, parents: ['root'] });
      console.log('folderId', folderId)

      // Gets the id of the first file with the specified metadata. 
      const fileId = await GDrive.files.getId(BACKUP_FILE_NAME, ['root', folderId], "application/json", false);
      console.log('fileId', filed) // even with a file existing inside the folder this return undefined

      if (typeof fileId === 'undefined') {
        return dispatch({ type: REQUEST_FAILED });
      }

      const response = await GDrive.files.get(fileId, { alt: 'media' });
      const backup = await response.json();

      dispatch({ type: FETCH_REMOTE_MOODS, payload: backup.moods });
      dispatch({ type: FETCH_REMOTE_ROUTINES, payload: backup.routines });
      dispatch({ type: FETCH_REMOTE_USERINFO, payload: backup.userInfo });
      dispatch({ type: FETCH_REMOTE_ACTIVITIES, payload: backup.activities });
      dispatch({ type: FETCH_REMOTE_CHALLENGES, payload: backup.challenges });
      dispatch({ type: FETCH_REMOTE_GRATITUDE_JOURNAL, payload: backup.gratitudeJournal });

      // notify that the request completed succesfully
      return dispatch({ type: REQUEST_SUCCESSFUL });
    } catch (error) {
      bugsnag.notify(error)
      return dispatch({ type: REQUEST_FAILED })
    }
  }
}
`````

**Comment by wmonecke** [comment]
<img width="312" alt="Screenshot 2020-10-15 at 14 52 22" src="https://user-images.githubusercontent.com/24256469/96128776-157a1c80-0ef6-11eb-8f87-c0df7db22a3d.png">

Apparently, Google decided to verify apps when accessing GDrive without telling us. Excellent!

**Comment by RobinBobin** [comment]
Hello!
I'm glad the lib is of use for you and I hope you'll manage to sort this issue out. Please tell me if there's anything I can do for you.
One small observation. `GDrive.init()` is meant to be invoked only once, when your app is started.  It just creates instances of necessary classes and has nothing to do with signing a user in.

By the way, what did you do to see the screen at the image you attached?

**Comment by wmonecke** [comment]
Hey there!
No actually that was wrong. I tried accessing the scope `drive` to see if I could manage to upload a file and then got presented with the screen above. When accessing scope `drive.file` you don't need app verification.

So I am back at the beginning. 
1) I am able to create a folder.
2) Unable to create a file within the folder (`Response 403 - Forbidden`)

I have no idea where to look. I assume this must be an auth problem and not your library.

**Comment by RobinBobin** [comment]
Hm... It seems strange they forbade uploading to subfolders. Maybe it really is an issue with scopes...

What if you try creating a folder at the root level and then create a file in that folder apart from your app logic? Just as a test.

**Comment by wmonecke** [comment]
Hi there! I solved this issue finally. 

As I said before I never had issues with the code.
When specifying the parents I thought you had to put the sequence of folders as in `root` -> `folderId` in sequential order like so `['root', folderId]`. This used to work and I thought I had to do this because the property `parents` is an array.

But if I just put `folderId` directly it works. I don't know what changed but this is working now:

````
await GDrive.files.createFileMultipart(
        uploadPayload,
        "application/json",
        { parents: [folderId], name: BACKUP_FILE_NAME },
        false,
      );
`````
Thank you for your quick response and for the amazing library!

**Comment by RobinBobin** [comment]
Oh, Jesus! That's our programming life :laughing: . Glad you have it working. You're welcome.

**Comment by wmonecke** [comment]
@RobinBobin Hey there! I always wondered why the property `parents` was an array instead of a string? Like usually a file has just one parent instead of multiple? I was always confused by this.😄

**Comment by RobinBobin** [comment]
Hey! Yeah, me too... I guess the guys who wrote the API know it :) .
--
Отправлено из Mail.ru для Android четверг, 22 октября 2020г., 12:42 +03:00 от Walter Monecke  notifications@github.com :

**Comment by wmonecke** [comment]
![6e3fd8dc258a9fa1dc80f08be32178e0](https://user-images.githubusercontent.com/24256469/96859172-7ad38d80-1461-11eb-84b1-5f0683996456.gif)
