### ISSUE TITLE
Updating the content of the file

### ISSUE THREAD

**Issue by cstehreem** [RobinBobin/react-native-google-drive-api-wrapper#38]
Is there a way to update the content of already uploaded file rather than just metadata?

The official documentation for [update](https://developers.google.com/drive/api/v3/reference/files/update) says it can be used to update a file's metadata OR content, I was wondering if we have the option to add content in the update using this wrapper?

Thanks

**Comment by RobinBobin** [comment]
It looks like `Files.update()` currently updates only the metadata. I'll gladly merge your PR if you decide to add the missing functionality.

**Comment by RobinBobin** [comment]
I'm looking into retrofitting this module, and I'll try to add the functionality you need.

**Comment by RobinBobin** [comment]
The functionality is added, finishing the docs.

**Comment by RobinBobin** [comment]
Please have a look at [v2](https://www.npmjs.com/package/@robinbobin/react-native-google-drive-api-wrapper) of this module. You can't manage permissions with it yet, but it will come very soon.
