### ISSUE TITLE
the documentation is not enough.

### ISSUE THREAD

**Issue by arungupta78** [RobinBobin/react-native-google-drive-api-wrapper#39]
I recently started using this library & i love this wrapper library for react native.

I am able to upload a file but not able to create a folder & generate shareable link for the uploaded file.
Can you please help me with that. It would be great if you can give some more examples in readme.md

**Comment by RobinBobin** [comment]
Yes, the examples are scarce. I think a FAQ will be great, but it  takes some time to gather these questions :smile: .

create a folder:

    await gdrive.files.newMetadataOnlyUploader()
      .setRequestBody({
        name: "folder",
        mimeType: MimeTypes.FOLDER,
        parents: ["root"]
      })
      .execute();

This should create a folder with the name "folder" at the root level.

> generate shareable link for the uploaded file
I'll think out how to do it with my lib :smile: .

**Comment by RobinBobin** [comment]
> generate shareable link for the uploaded file

1) You use `await gdrive.permissions.create()` to create a permission.
2) You use `await gdrive.files.getMetadata()` to get `webViewLink`. Looks like it's the link you want to obtain.

**Comment by arungupta78** [comment]
> Yes, the examples are scarce. I think a FAQ will be great, but it takes some time to gather these questions 😄 .
> 
> create a folder:
> 
> ```
> await gdrive.files.newMetadataOnlyUploader()
>   .setRequestBody({
>     name: "folder",
>     mimeType: MimeTypes.FOLDER,
>     parents: ["root"]
>   })
>   .execute();
> ```
> 
> This should create a folder with the name "folder" at the root level.
> 
> > generate shareable link for the uploaded file
> 
> I'll think out how to do it with my lib 😄 .

Through this am able to create a folder but how can i make it work like : If it's not created then create & return id otherwise just return id of existing one.

**Comment by RobinBobin** [comment]
Well, I think one way is reading the docs thoroughly and finding `Files.createIfNotExists()`.

**Comment by arungupta78** [comment]
I did find it & used it in different ways, it kept on giving UnexpectedFileCountError

**Comment by RobinBobin** [comment]
This is what you're saying: create a folder with the name "folder", if a folder with the name "random" doesn't exist. Is it what you meant?

Another thing. Maybe it's a typo in your post, not in your code, but you have an extra comma:

    gDrive.files.newMetadataOnlyUploader(), .setRequestBody(...)

**Comment by arungupta78** [comment]
I was saying, create a folder with name "Random" & there's already a folder with same name then just return the id of that folder & don't create another one.

**Comment by RobinBobin** [comment]
I see. That's the inconsistency I'm talking about. I hope you see it clearly now.

**Comment by arungupta78** [comment]
Can't see the issue 😶. I tried the createIfnotexists with multiple uploader types & diff query params.

**Comment by RobinBobin** [comment]
If you want to create a folder with the name "Random" if it doesn't exist and get its metadata otherwise, the call should be something like

```
await gDrive.files.createIfNotExists({
   name: 'Random',
   mimeType: MimeTypes.FOLDER,
   parents: ['root']
}, gDrive.files.newMetadataOnlyUploader()
   .setRequestBody({
      name: 'Random',
      mimeType: MimeTypes.FOLDER,
      parents: ['root']
   }));
```

And bear in mind, that the call returns an object, not an id.

**Comment by arungupta78** [comment]
I'd tried this one, as mentioned above. Tried again : 
![image](https://user-images.githubusercontent.com/31176941/123463756-85a27b80-d609-11eb-8eee-0fdae8d4db25.png)
But Still the same. UnexpectedFileCountError.

**Comment by RobinBobin** [comment]
Hmm... What will be the result if you list files with this criteria? Just invoke `gdrive.files.list()`.

**Comment by arungupta78** [comment]
Seems like it is fetching all the files. 
![image](https://user-images.githubusercontent.com/31176941/123507109-5b8e9f00-d685-11eb-8592-84419fd25d6f.png)
![image](https://user-images.githubusercontent.com/31176941/123507110-5df0f900-d685-11eb-89ac-eb40431ccd9f.png)

**Comment by arungupta78** [comment]
I wonder why reateIfNotExists isn't working. Actually i used the old google-drive-api-wrapper lib & that had a method createFolder which was working perfectly fine.

**Comment by RobinBobin** [comment]
Can you post a screenshot of `console.log(listRes)` with the file metadata?

**Comment by RobinBobin** [comment]
Eh... No, no screenshots are necessary. You're passing invalid query parameters to `list()`. If you look thoroughly at the docs of that google api method, you'll see, that the query is supplied through the `q` field of query parameters. That is,

```
gdrive.files.list({q: {}});
```

And the query is not an object, but a string.

**Comment by arungupta78** [comment]
![image](https://user-images.githubusercontent.com/31176941/123517226-7f6dd700-d6bd-11eb-9b9a-e1ad30b4d76a.png)
Thanks a lot bro. It's working now.

**Comment by RobinBobin** [comment]
Great.

Please close the issue if everything is sorted out.
