### ISSUE TITLE
Upload files to shared drive [404 error]

### ISSUE THREAD

**Issue by JorgeFeijoom** [RobinBobin/react-native-google-drive-api-wrapper#41]
Hi there,

We have been using rn-gd-api-wrapper for a while and the uploading files to a shared drive functionality has stopped working in our project.

Uploading files to the user's drive works, but uploading it to a shared drive using the drive's id returns a 404 error.

This is our code:

```
uploadFile: async function (file, callback) {
    const params = {
      files: {
        boundary: 'foo_bar_baz',
      },
    };
    GDrive.init(params);
    if (GDrive.isInitialized()) {
      GDrive.files
        .createFileMultipart(
          file.content,
          file.mimeType,
          {
            parents: file.parents,
            name: file.name,
          },
          true,
        )
        .then((res) => {
          console.log(res);
          return callback(res);
        });
    }
 },
```

Where file :

```
{ "content": CONTENT, mimeType": "application/pdf", "name": NAME, "parents": [IDSHAREDDRIVE], "path": PATH` }
```

The result is ( console.log(res) ):

```
{"_bodyBlob": {"_data": {"__collector": [Object], "blobId": BLOBID, "offset": 0, "size": 306}}, "_bodyInit": {"_data": {"__collector": [Object], "blobId": BLOBID, "offset": 0, "size": 306}}, "bodyUsed": false, "headers": {"map": {"alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"", "content-length": "306", "content-type": "application/json; charset=UTF-8", "date": "Wed, 30 Jun 2021 13:39:17 GMT", "server": "UploadServer", "vary": "Origin, X-Origin", "x-guploader-uploadid": ID}}, "ok": false, "status": 404, "statusText": undefined, "type": "default", "url": "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"}
```

We obtain the session token using GoogleSignin and all the necessary permissions for the shared drive are applied correctly, it worked until a while ago. Folders are also created within the shared drive but the file upload fails.

What could be te problem?

Cheers!

**Comment by RobinBobin** [comment]
Hi,

I can't say for sure, but one thing seems strange to me. Why are setting `isBase64 = true` if your file is a PDF (the last parameter to `createFileMultipart()`)?

Can you issue your request manually, without my lib?

BTW, I deprecated this package, and there's a new one, https://www.npmjs.com/package/@robinbobin/react-native-google-drive-api-wrapper. I'm not saying moving to the new version will solve your problem, but tried to make it more user-friendly.

**Comment by JorgeFeijoom** [comment]
Hi Robin, thanks for your answer.

The content of many files including images, sounds, pdf and documents were downloaded and uploaded as base64 without any problem.

It is probably a permission problem that we will check to rule out possible errors.

We will give the new package a try, thanks!
