### ISSUE TITLE
Robin Bobin help me , How can I  get all file of folder ? I try find resolve in document , but cannot do it.

### ISSUE THREAD

**Issue by TienNguyen2803** [RobinBobin/react-native-google-drive-api-wrapper#42]

**Comment by RobinBobin** [comment]
I don't know what you mean by "I try find resolve in document"... what exactly are you trying to find, but this can be accomplished with listing files and specifying the parent folder id in the query string.

https://developers.google.com/drive/api/v3/search-files
https://developers.google.com/drive/api/v3/ref-search-terms

**Comment by TienNguyen2803** [comment]
@RobinBobin  sorry, my English is a bit bad. I want to get a list image of a folder. 
I  have obtained the folder listing, next I want to get the list of images in a folder 
Help me pls.
```
  const file = await googleDriver.files.list({
        q: new ListQueryBuilder().e(
          "mimeType",
          "application/vnd.google-apps.folder"
        ),
      });
```

**Comment by RobinBobin** [comment]
No worries, I'm here to help :) .

[`list()`](https://github.com/RobinBobin/react-native-google-drive-api-wrapper/tree/master/src#filesfiles_list) returns an object with several fields, one of which is `files`. It's an array of objects. This array is empty if nothing is found. Each object contains info about one of the found entries. You can get your folder id this way.

Then you issue another query, listing all the files in that folder (with the `parents` keyword) of the corresponding mime type (with the `mimeType` keyword).

BTW, [MimeTypes](https://github.com/RobinBobin/react-native-google-drive-api-wrapper/tree/master/src#mime_types) have several handy constants defined.

**Comment by TienNguyen2803** [comment]
Thanks, @RobinBobin. I have found listing items in a folder with query second!
