### ISSUE TITLE
Help me , I want to upload image ( jpg) to google drive . I execute code not working

### ISSUE THREAD

**Issue by TienNguyen2803** [RobinBobin/react-native-google-drive-api-wrapper#43]
@RobinBobin help me, please!
 
```
 const id = (
        await googleDriver.files
          .newMultipartUploader()
          .setData(BBImage, "image/jpg")
          .setRequestBody({
            name: "image_123",
          })
          .execute()
      ).id;
      
      console.log(id);
```

**Comment by RobinBobin** [comment]
How exactly does it fail? And what are the scopes you're using to configure your google sign in?

**Comment by TienNguyen2803** [comment]
@RobinBobin scope I open full : 
 ```
 const config = {
      iosClientId: `300445652573-bbhpo7l5tivkt6h1ksl19to34o6dfd6s.apps.googleusercontent.com`,
      androidClientId: `300445652573-jbovbji45agkje9asegel9neamgvom0l.apps.googleusercontent.com`,
      scopes: [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.appdata",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/drive.metadata",
        "https://www.googleapis.com/auth/drive.metadata.readonly",
        "https://www.googleapis.com/auth/drive.photos.readonly",
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/drive.scripts",
      ],
    };
```
And BBImage  : is a Picture JPG  :
` import BBImage from "../../Assets/Images/blackboard.jpg";`
I Upload success to drive , but result in PDF and can not open.
 
![123](https://user-images.githubusercontent.com/46790025/124790168-25022f80-df75-11eb-9a32-6a89744229f9.png)

**Comment by RobinBobin** [comment]
1) androidClientId - what's this? I suppose you're using [this](https://www.npmjs.com/package/@react-native-google-signin/google-signin) package and I can't find that field in the docs.
2) As far I I understand, `import BBImage from "../../Assets/Images/blackboard.jpg";` doesn't give you the contents of the file. It gives you just a handle to be used to display the image. So I guess you need a way to read the contents of the file.

**Comment by TienNguyen2803** [comment]
@RobinBobin  I think too, I sure I open full scope.
The problem is BBImage, I will convert to base64 to upload.
I hope the upload success.
@RobinBobin  I think you have an example for upload images in the document  : 
https://www.npmjs.com/package/@robinbobin/react-native-google-drive-api-wrapper
It's amazing. I think people really need it,

**Comment by TienNguyen2803** [comment]
@RobinBobin  Today I research, I did upload jpg to google drive.
I convert the image to base64. The mimeType of document 
https://www.npmjs.com/package/@robinbobin/react-native-google-drive-api-wrapper
 missing type "image/jpg" . 
```
const id = (
          await googleDriver.files
            .newMultipartUploader()
            .setData(info_image.pickerResult.base64, "'image/jpg'")
            .setRequestBody({
              name: "image.jpg",
              mimeType: "image/jpg",
              parents: ["1M5BQ_NJVDrkeB5bi_uYmkGgi5qOmvi3N"],   // folderId , if you want to upload to folder
            })
            .setIsBase64(true)
            .execute()
        ).id;
```
