### ISSUE TITLE
Gdrive can get content file xml 

### ISSUE THREAD

**Issue by TienNguyen2803** [RobinBobin/react-native-google-drive-api-wrapper#46]
@RobinBobin  Can you support me get content file with `mimeType = "application/xml"`
my Code get xml file to reponse Blob : 
File has mimeType = "plain/text"  . but mimeType = "text/xml" I can get text content .
@RobinBobin would you suggest me some ideas?
```
const xml = await googleDriver.files.get(file.id, { alt: "media" });
 var blobs = xml._bodyBlob;
    const text = await this.blobToBase64(blobs);
    console.log(text);
```

```
 blobToText = (blob) => {
    const reader = new FileReader();
    reader.readAsText(blob);
    return new Promise((resolve) => {
      reader.onloadend = () => {
        resolve(reader.result);
      };
    });
  };
```
I want to get the content of the file XML from Google Drive.

**Comment by TienNguyen2803** [comment]
Sorry, the Code is right. My File XML is encoding js.

**Comment by RobinBobin** [comment]
Glad you have it sorted.
