### ISSUE TITLE
Can Upload file to google driver with react native version 0.64.1

### ISSUE THREAD

**Issue by Dat0319** [RobinBobin/react-native-google-drive-api-wrapper#47]
I have an error when try to use your lib to control file with google driver, you can check it in my repository in this link below
https://github.com/Dat0318/RN_example_firebase
i am follow a tutorial to use your lib 
https://aboutreact.com/react-native-google-drive/ 
i looking forwards your feedbacks.
Thanks a lots.
```
bodyUsed: false
headers: Headers
map:
alt-svc: "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
cache-control: "private, max-age=0"
content-security-policy: "frame-ancestors 'self'"
content-type: "application/json; charset=UTF-8"
date: "Sun, 08 Aug 2021 10:55:00 GMT"
expires: "Sun, 08 Aug 2021 10:55:00 GMT"
server: "GSE"
transfer-encoding: "chunked"
vary: "Origin, X-Origin"
www-authenticate: "Bearer realm=\"https://accounts.google.com/\", error=insufficient_scope, scope=\"https://www.googleapis.com/auth/drive\""
x-content-type-options: "nosniff"
x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
[[Prototype]]: Object
[[Prototype]]: Object
ok: false
status: 403
statusText: ""
type: "default"
url: "https://www.googleapis.com/drive/v3/files?q=name=%22AboutReactAppExample%22%20and%20trashed=false%20and%20mimeType=%22application/vnd.google-apps.folder%22%20and%20%27root%27%20in%20parents"
_bodyBlob: Blob
_data:
blobId: "86a7ff9e-1beb-4369-bb87-252ff8c7ff0a"
offset: 0
size: 306
__collector: null
[[Prototype]]: Object
data: (...)
size: (...)
type: (...)
[[Prototype]]: Object
_bodyInit: Blob
_data: {size: 306, offset: 0, blobId: "86a7ff9e-1beb-4369-bb87-252ff8c7ff0a", __collector: null}
data: (...)
size: (...)
type: (...)
[[Prototype]]: Object
[[Prototype]]: Object
```

**Comment by Dat0319** [comment]
Can you make a readme to tutorial me use your library and beautiful if you have an example. <3

**Comment by RobinBobin** [comment]
I deprecated the package mentioned in the article and wrote a new version.

https://github.com/RobinBobin/react-native-google-drive-api-wrapper/tree/master/src

Please post your code that fails here.

**Comment by Dat0319** [comment]
Thanks for your feedback.
this is my code:
https://github.com/Dat0318/RN_example_firebase/blob/master/RN_example_base/screens/Drive.tsx
and you can check project in this link :
https://github.com/Dat0318/RN_example_firebase
i use the repo to practice and do an example before add to my projects.
thanks

**Comment by RobinBobin** [comment]
You're welcome.

I saw the link to your repo. Sorry, I don't have time to examine all your code. Can you post only the relevant part?

Actually https://github.com/RobinBobin/react-native-google-drive-api-wrapper/tree/master/src has an example how to upload a file.

**Comment by Dat0319** [comment]
yes, i will try this.

**Comment by RobinBobin** [comment]
I hope you got it sorted. I'll close the issue.
