### ISSUE TITLE
Problem in call gdrive.files.list(

### ISSUE THREAD

**Issue by edersonfaccin** [RobinBobin/react-native-google-drive-api-wrapper#49]
Hello evebody, i was using this api, but, in call gdrive.files.list it's returned this response.

{"__response":{"type":"default","status":401,"ok":false,
...
"code":401,"message":"Invalid Credentials"

But my credentials i am utilizing this way 

GoogleSignin.configure({
            webClientId: this credential i was generate in google api console,
            offlineAccess: true,
            scopes: [
                'https://www.googleapis.com/auth/drive',
                'https://www.googleapis.com/auth/drive.file'
            ],
        })

And i had called this way

await gdrive.files.list({
    "corpus": "user", 
    "includeItemsFromAllDrives": true, 
    "includeTeamDriveItems": true, 
    "supportsAllDrives": true, 
    "supportsTeamDrives": true
  }).then(res => {
    console.log(1, res.json())
  }).catch(err => {
    console.log(2, JSON.stringify(err))
  })

Someone to know what i made wrong?

**Comment by RobinBobin** [comment]
Hi @edersonfaccin,

I'll try to address the issue in a couple of days, when I have some more time.

**Comment by RobinBobin** [comment]
1) Do you have any specific reasons to set `webClientId` and `offlineAccess`? I've always set only `scopes`.
1) I hope you didn't forget to do:
```
await GoogleSignin.signIn();

gdrive.accessToken = (await GoogleSignin.getTokens()).accessToken;
```
1) That's quite another question, but you're mixing up `async/await` with `then/catch` syntax in your call to `gdrive.files.list()`.

**Comment by edersonfaccin** [comment]
Hi, thanks for return.

1. webClientIde -> i have no reason to set webClientId and offlineAccess, i put because i did see in some posts. If i set only scopes continue the same problem.

2. No, i doing the await GoogleSignin.signIn(), was generated token with success.


i put only async/await and removed the then/catch and retested but continue returning status 401 error

**Comment by RobinBobin** [comment]
1) Are you sure you didn't miss the `gdrive.accessToken = (await GoogleSignin.getTokens()).accessToken;` part?
1) Try just listing the files, without params (`await gdrive.files.list()`).

**Comment by edersonfaccin** [comment]
Congrat, thank you so much, the first problem was this, I was storing the token in AsyncStorage, probably this token was invalid, so I did it in the way you mentioned.

i going to close this issue, thankful
