### ISSUE TITLE
can not createFileMultipart

### ISSUE THREAD

**Issue by uendar** [RobinBobin/react-native-google-drive-api-wrapper#5]
I try to  createFileMultipart using the example but it returnes 400?
Any example how can i upload files on Gdrive please?

**Comment by RobinBobin** [comment]
Hi there!

Thanks for posting your issue.

Are you sure you signed in properly?
Do other methods from my module work for you?

**Comment by uendar** [comment]
Hi,
Yes i am sure. I tried this:
```
 GDrive.setAccessToken(this.state.accesToken);
        GDrive.init();
        GDrive.isInitialized() ? return true:return false
```

These methods work. But now i want to save a document file in gdrive and i get 403. Can you help me with this ?

**Comment by RobinBobin** [comment]
Are you sure the first parameter you supply to GDrive.files.createFileMultipart() is correct?

That's what's written in the readme:

const contents = "My text file contents";
 // or
 const contents = [10, 20, 30];
 
 GDrive.files.createFileMultipart(
     contents,
     "corresponding mime type", {
         parents: ["root"],
         name: "My file"
     });

**Comment by uendar** [comment]
I know i tried like you say but not successfully. So how can we upload a file in gdrive? Do you have an example ?  I have tried with RNFetchBlob too but not working:


   ```
   RNFetchBlob.fetch('POST', 'https://www.googleapis.com/upload/drive/v3/files?uploadType=media',{
            Authorization : this.state.accesToken,
            'Content-Type' : 'multipart/form-data',
        }, [file])
        .then((res) => {
           console.log("response in success" + res.text())
       })
       .catch((err) => {
          console.log("response in error" + err)
       })
```

**Comment by RobinBobin** [comment]
Did you enable the api in the google developer console?

Are you sure your credentials are correct? You can check it uploading a file to google drive.

Unfortunately I don't have a working example at hand.

As for RNFetchBlob I guess I've never used it, so I'm unable to comment on that.


>Вторник, 11 декабря 2018, 19:59 +03:00 от uendar <notifications@github.com>:
>
>I know i tried like you say but not successfully. So how can we upload a file in gdrive? Do you have an example ?  I have tried with RNFetchBlob too but not working:
>RNFetchBlob.fetch('POST', 'https://www.googleapis.com/upload/drive/v3/files?uploadType=media',{
>         Authorization : this.state.accesToken,
>         'Content-Type' : 'multipart/form-data',
>     }, [file])
>     .then((res) => {
>        console.log("response in success" + res.text())
>    })
>    .catch((err) => {
>       console.log("response in error" + err)
>    })
>
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Рубен Шалимов

**Comment by uendar** [comment]
Yes google api are enabled. I don't know where the problem is ...

**Comment by RobinBobin** [comment]
I'm closing the issue, as it's been inactive for a while. Please don't hesitate to reopen if needed.

**Comment by sudhiryadav** [comment]
I am facing the same issue. Did someone find anything? @uendar were you able to solve your issue?

**Comment by Moonubanna** [comment]
> Are you sure the first parameter you supply to GDrive.files.createFileMultipart() is correct?
> 
> That's what's written in the readme:
> 
> const contents = "My text file contents";
> // or
> const contents = [10, 20, 30];
> 
> GDrive.files.createFileMultipart(
> contents,
> "corresponding mime type", {
> parents: ["root"],
> name: "My file"
> });

Hello @RobinBobin i try to upload "image" using your library i have issue in my google drive "No previous available". what i do.

**Comment by MehdiRaza1998** [comment]
The same problem for me, anyone solved? please help, I am also getting 403 error

**Comment by RobinBobin** [comment]
Hi, everyone!

Sorry you have troubles using my module. Unfortunately I'm a bit busy right now, so I can't look into the issue. But I'll try to do my best as soon as possible.

**Comment by MehdiRaza1998** [comment]
I solved my problem of creating a simple text file , my problem was I was using wrong scope. @RobinBobin you probably should have mentioned that we should configure GoogleSignin like:

        GoogleSignin.configure({
        scopes: ['https://www.googleapis.com/auth/drive'],
        });

In the documentation of react-native-google-signin we have 

        scopes: ['https://www.googleapis.com/auth/drive.readonly'], // which makes it only READONLY 

The problem I am facing now is, how can I upload a .realm file, it is not an image. So what changes should I make to upload a file with a different format. Your answer will be more than appreciated.

**Comment by MehdiRaza1998** [comment]
Solved it, I had to change the mimetype to "'*/*'", with this every file can be uploaded but with no format I guess.

                 var fs = require('react-native-fs');

        fs.readFile(Realm.defaultPath, 'base64').then(res => {
          GDrive.files
            .createFileMultipart(
              res,
              "'*/*'",
              {
                parents: ['root'], //or any path
                name: 'mybackupRealm',
              },
              true,
            )
            .then(response => {
             alert(JSON.stringify(response))
            //  alert(response.status)  //if 200, that means it is uploaded
             
            }).catch = err => {
            console.log('error', err);
            alert(err);
          };
        });

**Comment by RobinBobin** [comment]
Dear friends!
I want to close this issue, as it seems to be about rather unrelated problems. Please create new issues with the exact problems you're experiencing.

Thanks.

**Comment by pradipk801298** [comment]
> To be correct the way i do is:
> 
> ```
> googleWrapper = ()=> {
>     
>         GDrive.setAccessToken(this.state.accesToken);
>         GDrive.init();
>         GDrive.isInitialized() ? console.log("TRUEEEEEEEE"):console.log("FALSEEEEEEEE")
> 
>         let file = { fileName: '1544534141015Screenshot_20181114-153207-2.png',
>         type: 'image/png',
>         path: '/storage/emulated/0/Download/PersonalRecords/1544534141015Screenshot_20181114-153207-2.png',
>         uri: 'content://com.android.providers.media.documents/document/image%3A11651' }
> 
>          GDrive.files.createFileMultipart(file, file.type, { parents: ['root'], name: file.fileName })
>          .then((res)=>{console.log(res)})
>          .catch((e)=>{console.log(e)})
>     }
> ```
> 
> the file variable are true values when i select file from phone storage. But i get 403!
> 
> ```
>  { type: 'default',
> :   status: 403,
> :   ok: false,
> :   statusText: undefined,
> :   headers:
> :    { map:
> :       { 'alt-svc': [ 'quic=":443"; ma=2592000; v="44,43,39,35"' ],
> :         server: [ 'UploadServer' ],
> :         date: [ 'Tue, 11 Dec 2018 14:25:52 GMT' ],
> :         'content-length': [ '962' ],
> :         'content-type': [ 'application/json; charset=UTF-8' ],
> :         vary: [ 'X-Origin' ],
> :         'x-guploader-uploadid': [ 'AEnB2UrZs2_J0OwgqfpMX6Ml1Mp1cluIi8oiFFjNpX
> qSQSHxflGbBoXovjSVXw0KKP_j9qc7fzRkwU477bh0zCu9rW-4UPVzSAt7CQnG97yEfb28jLakOn4' ] } },
> :   url: 'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart
> ',
> :   _bodyInit:
> :    { _data:
> :       { size: 962,
> :         offset: 0,
> :         blobId: '54691175-9941-4308-b015-991e8caa986b' } },
> :   _bodyBlob:
> :    { _data:
> :       { size: 962,
> :         offset: 0,
> :         blobId: '54691175-9941-4308-b015-991e8caa986b' } } }
> ```

same issue i am also facing
