### ISSUE TITLE
How long does the GDrive access token live?

### ISSUE THREAD

**Issue by losh11** [RobinBobin/react-native-google-drive-api-wrapper#50]
I'm very interested in using this project for auto-uploading hidden backup files to the users Google Drive. This backup occurs infrequently. Sometimes during the same sessions, or often during multiple app sessions (where the device may be rebooted, or app force killed, suspended etc). So I'm wondering how long does the GDrive access token stay alive? I would like to minimise the number of signins as possible, because I feel this may not be good UX.

**Comment by RobinBobin** [comment]
I don't have a slightest idea, actually :slightly_smiling_face: . It's up to a user of my module which module to use for google sign in. I think it's ok to save the access token with async storage or something alike. Sooner or later one of the methods you use to access google drive with fail with an authorization error message. You can re-authenticate then.

**Comment by RobinBobin** [comment]
Even better. `@react-native-google-signin/google-signin` has a message `signInSilently()`. I think that's your choice.

**Comment by RobinBobin** [comment]
It's been inactive for a while, so I'll close it. Please reopen if you need to.
