### ISSUE TITLE
Don't have timeout when lost connection

### ISSUE THREAD

**Issue by huyopen** [RobinBobin/react-native-google-drive-api-wrapper#53]
I tested 2 case:
+ Case 1: Turn off wifi and mobile network => your lib worked perfectly, it throw a connection error.
+ Case 2: Turn on wifi or turn on mobile network but keep these connections can't access to internet. In this case, your library don't throw anything, it wait forever.
Can you add timeout to fetch please?
Sorry for my English.

**Comment by RobinBobin** [comment]
Hi there,
Thanks for pointing this out to me :+1: . I guess it's a needed feature. I'll sort it out and update you.

**Comment by RobinBobin** [comment]
I uploaded the new version along with the README to [npmjs](https://www.npmjs.com/package/@robinbobin/react-native-google-drive-api-wrapper).

**Comment by RobinBobin** [comment]
Looks like it's working properly. I'll close the issue.
