### ISSUE TITLE
Upload files get error

### ISSUE THREAD

**Issue by huyopen** [RobinBobin/react-native-google-drive-api-wrapper#55]
When i use upload, it return code: 0. I think it cause by AbortController. 
Can you check it again sir? Thank you so much.
```
try {
    const res = await driver.files
      .newMultipartUploader()
      .setData(base64, "'image/jpg'")
      .setRequestBody({
        name: imageName,
        mimeType: 'image/jpg',
        parents: [folderId],
      })
      .setIsBase64(true)
      .execute();
  } catch (err) {
    console.log('Upload file error: ', err);
    throw err;
  }
```

**Comment by RobinBobin** [comment]
1) You have a typo, I guess: `.setData(base64, "'image/jpg'")`, namely `"'image/jpg'"` (you use both `"` and `'`).

2) > When i use upload, it return code: 0

Does it throw or return?

3) Please paste your code that setups my package.

**Comment by huyopen** [comment]
1. sorry sir, I double check it:
```
export const uploadImageToFolder = async (
  driver,
  folderId,
  imageName = 'test.jpg',
  base64,
) => {
  //   folderId = "1M5BQ_NJVDrkeB5bi_uYmkGgi5qOmvi3N"; // example
  try {
    const res = await driver.files
      .newMultipartUploader()
      .setData(base64, 'image/jpg')
      .setRequestBody({
        name: imageName,
        mimeType: 'image/jpg',
        parents: [folderId],
      })
      .setIsBase64(true)
      .execute();
    return res.id;
  } catch (err) {
    console.log('Upload file error: ', err);
    throw err;
  }
};
```
2. It going to catch error block which is: "Upload file error:  [AbortError: Aborted]". 
I have an image which show how api return code 0.
![image](https://user-images.githubusercontent.com/48566584/146356103-ccf0dce8-005a-46ed-81da-c8cc952e49b4.png)

3. I think it doesn't cause by my code, because when I degrade your lib at version 0.6, it don't have any error, api return 200

**Comment by RobinBobin** [comment]
> 3\. I think it doesn't cause by my code, because when I degrade your lib to version 0.6, it doesn't have any error, api return 200

Well, version 0.6 doesn't use `AbortController`. Maybe increasing the [timeout](https://github.com/RobinBobin/react-native-google-drive-api-wrapper/tree/master/src#gdriveapi_fetch_timeout) will solve your issue?

**Comment by huyopen** [comment]
I try increase timeout to 15000 (15s i think) and it doesn't throw any error.  Can you increase it to 15000?

**Comment by RobinBobin** [comment]
You mean you want me to make 15000 ms a default value? What for?

**Comment by RobinBobin** [comment]
I'll close the issue as it has been inactive for a while. Please reopen, if you need to.

**Comment by woochoon** [comment]
Hi Robin, I experienced the same issue with huyopen. 
Can you tell me how can I increase the timeout value? I have tried these attempts below with no luck```
GDriveServices.fetchTimeout(15000)
GDriveServices.fetchTimeout = 15000
```
Thanks a lot!

**Comment by RobinBobin** [comment]
Hi there,

`GDriveServices.files.fetchTimeot = number`

or

`GDriveServices.about.fetchTimeot = number`

, whichever API you need. The timeout is set separately.

Cheers.

**Comment by woochoon** [comment]
What a speedy response. Thanks!
