### ISSUE TITLE
Create a folder and save file in that folder

### ISSUE THREAD

**Issue by pritsawa** [RobinBobin/react-native-google-drive-api-wrapper#56]
I want to create a folder and save file in that folder. Can you please check below code and tell me whats wrong with it. I couldn't find such example in the documentation

 ```
gdrive.files
        .createIfNotExists(
          {
            q: new ListQueryBuilder()
              .e('name', 'MyFolder')
              .and()
              .e('mimeType', MimeTypes.FOLDER)
              .and()
              .in('root', 'parents'),
          },
          gdrive.files
            .newMultipartUploader()
            .setData(content, MimeTypes.TEXT)
            .setRequestBody({
              name: 'myfile.txt',
              parents: ['MyFolder'],
            }),
        )
        .execute();
```

**Comment by RobinBobin** [comment]
1) `.execute()` must be dropped. It's invoked internally, as stated in the docs.
1) What you wrote is: create a text file `myfile.txt` in the folder `MyFolder` if folder `MyFolder` doesn't exist in `root`.
1) If you wan't to create a folder if it doesn't exist, `queryParameters` should be as you wrote, but `uploader` should be something like

    ```
    gdrive.files.newMetadataOnlyUploader()
      setRequestBody({
        name: "MyFolder",
        mimeType: MimeTypes.FOLDER,
        parents: ["root"]
    }));
    ```

1) `createIfNotExists()` must be invoked again if you want to create a file if it doesn't exist.

**Comment by pritsawa** [comment]
```
gdrive.files
       .createIfNotExists(
         {
           q: new ListQueryBuilder()
             .e('name', 'MyFolder')
             .and()
             .e('mimeType', MimeTypes.FOLDER)
             .and()
             .in('root', 'parents'),
         },
       );

gdrive.files.newMetadataOnlyUploader()
  setRequestBody({
    name: "MyFolder",
    mimeType: MimeTypes.FOLDER,
    parents: ["root"]
}))

gdrive.files
           .newMultipartUploader()
           .setData(content, MimeTypes.TEXT)
           .setRequestBody({
             name: 'myfile.txt',
             parents: ['MyFolder'],
           })
```

Do you mean something like the above?.

I want to create a folder if its not present but want to create a file irrespective of whether its present or not as i need to update the file to google drive every few hours

**Comment by pritsawa** [comment]
I tried something like this as well

```
await gdrive.files.createIfNotExists(
        {
          q: new ListQueryBuilder()
            .e('name', 'MyFolder')
            .and()
            .e('mimeType', MimeTypes.FOLDER)
            .and()
            .in('root', 'parents'),
        },
        await gdrive.files.newMetadataOnlyUploader().setRequestBody({
          name: 'MyFolder',
          mimeType: MimeTypes.FOLDER,
          parents: ['root'],
        }),
      );

      const fileId = (
        await gdrive.files
          .newMultipartUploader()
          .setData(content, MimeTypes.TEXT)
          .setRequestBody({
            name: 'youredge.txt',
            parents: ['MyFolder'],
          })
          .execute()
      ).id;
```

But i get an error message saying file not Found "MyFolder"

**Comment by RobinBobin** [comment]
Are your permissions ok?

I'll create an example project and upload it to github.

**Comment by pritsawa** [comment]
@RobinBobin  By permissions You mean scopes in my google sign in call correct? Below are my scopes

  ```
scopes: [
          'https://www.googleapis.com/auth/drive.appdata',
          'https://www.googleapis.com/auth/drive.file',
          'https://www.googleapis.com/auth/drive.metadata',
        ],
```

**Comment by RobinBobin** [comment]
Yes, I guess that's what I meant :smiley: . My scopes are:

    scopes: [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appfolder"
    ]

**Comment by pritsawa** [comment]
ok i will change it the above one. 

1. ```
gdrive.files
       .createIfNotExists(
         {
           q: new ListQueryBuilder()
             .e('name', 'MyFolder')
             .and()
             .e('mimeType', MimeTypes.FOLDER)
             .and()
             .in('root', 'parents'),
         },
         gdrive.files
           .newMultipartUploader()
           .setData(content, MimeTypes.TEXT)
           .setRequestBody({
             name: 'myfile.txt',
             parents: ['MyFolder'],
           }),
       )


```
2. ```
await gdrive.files.createIfNotExists(
        {
          q: new ListQueryBuilder()
            .e('name', 'MyFolder')
            .and()
            .e('mimeType', MimeTypes.FOLDER)
            .and()
            .in('root', 'parents'),
        },
        await gdrive.files.newMetadataOnlyUploader().setRequestBody({
          name: 'MyFolder',
          mimeType: MimeTypes.FOLDER,
          parents: ['root'],
        }),
      );

      const fileId = (
        await gdrive.files
          .newMultipartUploader()
          .setData(content, MimeTypes.TEXT)
          .setRequestBody({
            name: 'youredge.txt',
            parents: ['MyFolder'],
          })
          .execute()
      ).id;
```

Which one accroding to you is correct? First one or second one?
My use case create a folder if not present and then add a file to that folder.

**Comment by RobinBobin** [comment]
second

**Comment by RobinBobin** [comment]
You might need to specify the folder id, not name.

**Comment by RobinBobin** [comment]
I added a [link](https://github.com/RobinBobin/react-native-google-drive-api-wrapper/tree/master/src#usage) to my example project.

**Comment by pritsawa** [comment]
@RobinBobin  You mean something like below

```
const folderId = await gdrive.files.createIfNotExists(
        {
          q: new ListQueryBuilder()
            .e('name', 'MyFolder')
            .and()
            .e('mimeType', MimeTypes.FOLDER)
            .and()
            .in('root', 'parents'),
        },
        await gdrive.files.newMetadataOnlyUploader().setRequestBody({
          name: 'MyFolder',
          mimeType: MimeTypes.FOLDER,
          parents: ['root'],
        }),
      ).id;

      const fileId = (
        await gdrive.files
          .newMultipartUploader()
          .setData(content, MimeTypes.TEXT)
          .setRequestBody({
            name: 'youredge.txt',
            folderId: folderId,
          })
          .execute()
      ).id;
```

**Comment by pritsawa** [comment]
The above thing does not work

**Comment by RobinBobin** [comment]
The phrase "doesn't work" means nothing at all. How exactly doesn't it work?

Also please have a look at the relevant piece of code in the example project I linked.

**Comment by RobinBobin** [comment]
I think your folder creation code block has two errors. One seems harmless, the other is principal. Compare this code block to the second one.

**Comment by pritsawa** [comment]
i think it is similar to the second one. The only thing i dont understand is how to get the folder Id. After going throught your sample project i did something like below but i dont get the folder id

```
const folderId = (
        await gdrive.files
          .newMetadataOnlyUploader()
          .setRequestBody({
            name: 'Folder',
            mimeType: MimeTypes.FOLDER,
            parents: ['root'],
          })
          .execute()
      ).id;
```

**Comment by pritsawa** [comment]
This worked for me thanks

```
 const folderId = await gdrive.files
        .newMetadataOnlyUploader()
        .setRequestBody({
          name: 'tanay',
          mimeType: MimeTypes.FOLDER,
          parents: ['root'],
        })
        .execute();

      const fileId = (
        await gdrive.files
          .newMultipartUploader()
          .setData(content, MimeTypes.TEXT)
          .setRequestBody({
            name: 'tanay.txt',
            parents: [JSON.parse(JSON.stringify(folderId)).id],
          })
          .execute()
      ).id;

      setGoogleFileId('Success ok ' + fileId);
```

**Comment by RobinBobin** [comment]
Glad you got it working, but 

1. Your folder will always be created.
1. Your code is overcomplicated as `JSON.parse / stringify` are unnecessary. `(await (...)). id` is what's needed.

**Comment by pritsawa** [comment]
`(await (...)). id` I have tried this but it doesn't work for me. Not sure why

**Comment by RobinBobin** [comment]
Well, it's up to you to make your code clumsy or not.

**Comment by RobinBobin** [comment]
Have a look at the following block of code in my sample project:

```
const createFolder = useCallback(async () => {
    console.log(await invoker(async () => (
      await gdrive.files.newMetadataOnlyUploader()
        .setRequestBody({
          name: "Folder",
          mimeType: MimeTypes.FOLDER,
          parents: ["root"]
        })
        .execute()
    )));
  }, [invoker]);
```

Its output is:

```
{"id": "some_id", "kind": "drive#file", "mimeType": "application/vnd.google-apps.folder", "name": "Folder"}
```

If you modify it as

```
const createFolder = useCallback(async () => {
    console.log(await invoker(async () => (
      (await gdrive.files.newMetadataOnlyUploader()
        .setRequestBody({
          name: "Folder",
          mimeType: MimeTypes.FOLDER,
          parents: ["root"]
        })
        .execute()).id
    )));
  }, [invoker]);
```

(mind the parentheses before `await` and after `execute()`) the output will be

`some-id`

, i.e. the folder id.

**Comment by Dalu26** [comment]
> Are your permissions ok?
> 
> I'll create an example project and upload it to github.

What permissions are need? I'm currently experiencing this issue

**Comment by RobinBobin** [comment]
@Dalu26 please create a separate issue.
