### ISSUE TITLE
Uploaded sqlite file is 0 byte

### ISSUE THREAD

**Issue by przbadu** [RobinBobin/react-native-google-drive-api-wrapper#58]
Hi, I am really struggling to upload my sqlite backup file to google drive. If I do local backup, everything works fine, and I can view content of my sqlite backup in SQLite Viewer.

Where as if I try to upload that file to google drive using this library, I always get 0 byte sqlite file uploaded in google drive, which do not have any content in it.

Here is what I am doing right now:

```js
  async uploadToDrive(): Promise<void> {
    try {
      // const mimeType = 'application/x-sqlite3'; // I tried with different mime type
      const mimeType = MimeTypes.BINARY;
      const localDBFilePath = '/data/data/<my-package-name>/demo.db';
      const fileToBackup = RNFS.readFile(localDBFilePath, 'base64');
     // I have also tried, same result.
    // RNFetchBlog.fs.readStream(localDBFilePath, 'base64')
      const fileMetadata = {
        name: 'test.db',
        MimeTypes: mimeType,
      };

      const result = await this.gdrive.files
        .newMultipartUploader()
        .setData(fileToBackup, mimeType)
        .setRequestBody(fileMetadata)
        .execute();

      console.log('file uploaded to Drive: ', result.id);
    } catch (error: any) {
      alert('Error: ' + error.message);
    }
  }
```

If anyone can help me find, what I am doing wrong would be appreciated.

**Screenshots:**
![Screenshot_3](https://user-images.githubusercontent.com/4189129/149453781-605a5224-3b19-48ed-bb13-f00fee4094b5.png)
![Screenshot_4](https://user-images.githubusercontent.com/4189129/149453783-d6d468fb-e1d7-4d8b-862d-7cde94f027b9.png)

**Comment by RobinBobin** [comment]
I would try converting base64 to binary before uploading. I guess any RN project has the [base64-js](https://www.npmjs.com/package/base64-js) dependency. And only then upload to GDrive, setting whatever mime type you want.

**Comment by przbadu** [comment]
Thank you @RobinBobin for quick response, I will try it.

**Comment by przbadu** [comment]
https://github.com/RobinBobin/react-native-google-drive-api-wrapper/issues/3

**Comment by RobinBobin** [comment]
Glad you got it working :slightly_smiling_face: .

:smile: shame on me for not noticing the missing `await` and completely forgetting about `.setIsBase64()` :flushed:
