### ISSUE TITLE
How can i copy file to specific folder with file id? Please example. 

### ISSUE THREAD

**Issue by NgaChat** [RobinBobin/react-native-google-drive-api-wrapper#59]

**Comment by RobinBobin** [comment]
Hello NgaChat,
Unfortunately I'm currently busy on another project, so I won't be able to answer promptly.
You might have already noticed the method `copy` (just look for it in the readme). Honestly, I don't remember how to use it, but experimenting might help.

**Comment by RobinBobin** [comment]
Please combine what's written in the readme with https://developers.google.com/drive/api/v3/reference/files/copy. I'm sure it'll work.

**Comment by RobinBobin** [comment]
Did you manage to get it working?

**Comment by NgaChat** [comment]
> Did you manage to get it working?

I am working with https://developers.google.com/drive/api/v3/reference/files/copy.

**Comment by RobinBobin** [comment]
oh, that's great you found a way out. Could you close the issue please, if you got it solved?
