### ISSUE TITLE
"Could not find a declaration file for module 'react-native-google-drive-api-wrapper'"

### ISSUE THREAD

**Issue by jebuth** [RobinBobin/react-native-google-drive-api-wrapper#6]
Cannot build after installing.
`npm i --save react-native-google-drive-api-wrapper`
`react-native link react-native-fs`

Try `npm install @types/react-native-google-drive-api-wrapper` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-google-drive-api-wrapper';` [7016]

**Comment by RobinBobin** [comment]
After
```
react-native init GDriveTest
npm i --save react-native-google-drive-api-wrapper
react-native link react-native-fs
```
the app builds and installs on my device just fine.

I'm afraid I'm unfamiliar with TypeScript so there's no ```.d.ts```-file. I'm using this module in several projects and I've never had any problems related to the absence of this file.

**Comment by jebuth** [comment]
I'm not familiar with TypeScript either. Perhaps some other package in my project is causing this?

**Comment by RobinBobin** [comment]
Sounds like a very reasonable supposition to me.

**Comment by jebuth** [comment]
It turns out this was only a warning. I had multiple build errors and assumed this was the cause but it wasn't. The issue was with react-native-google-signin.

**Comment by RobinBobin** [comment]
I see. Thanks for pointing this out. I'll close the issue then, but feel free to submit any other requests.
