### ISSUE TITLE
Exception trying to update existing file

### ISSUE THREAD

**Issue by przbadu** [RobinBobin/react-native-google-drive-api-wrapper#60]
@RobinBobin 

Here, I already have existing file in google drive, and I am trying to update that file content by passing `setIdOfFileToUpdate(file.id)` but that is giving me `unhandled Promise Rejection (id: 0)` but file gets updated in google drive.

If I remove `setidOfFileToUpdate(file.id)` then it successfully upload duplicate file:

```js
    const file = await this.getFileMetadata();
    console.log(file);

    // upload new file or update existing file
    const uploader = this.gdrive.files
      .newMultipartUploader()
      .setData(fileToUpload, MimeTypes.BINARY)
      .setIsBase64(true)
      .setRequestBody({
        name: this.backupDbName,
        MimeTypes: MimeTypes.BINARY,
      });
    if (file.id) uploader.setIdOfFileToUpdate(file.id);
    const result = await uploader.execute();
```

![image](https://user-images.githubusercontent.com/4189129/151690567-ce972318-1d3f-49eb-9a3d-e99ed244a5a3.png)

**Comment by przbadu** [comment]
Basically, I can't perform further section after file is updated, like updating last updated timestamp.

**Comment by RobinBobin** [comment]
Sorry for a silly question, are you sure your `try/catch` block catches the possible exceptions?

What will happen if you surround `const result = await uploader.execute();` with a `try/catch`?

**Comment by przbadu** [comment]
@RobinBobin 

Yes, right now I am surrounding that whole method inside `try/catch` block, just to show error screen, I commented it.

In both case, if I do console log, I get `AbortError: Abort`

**Comment by RobinBobin** [comment]
Well, my only guess is that your current fetch timeout is insufficient. Try increasing it. Have a look at the readme, please.

It seems to me it will be worthwhile to make it possible to make fetch add infinitely.

**Comment by RobinBobin** [comment]
Starting with v1.1.0 [`GDriveApi.fetchTimeout`](#gdriveapi_fetch_timeout) can be set to a negative value to make `fetch()` wait infinitely.

**Comment by yagnikkorat** [comment]
Hello RobinBobin,
I have one query that How can I download the uploaded file on drive ?(I wanna download the file)
Please help me.

**Comment by RobinBobin** [comment]
Hello,
Please have a look at the docs and at the supplied example project. If something is unclear, please open another issue. I'll close this one, as it's been inactive for a while.
