### ISSUE TITLE
Get File Metadata

### ISSUE THREAD

**Issue by oliviayew** [RobinBobin/react-native-google-drive-api-wrapper#63]
I need help to get metadata of the files (Google Drive API V3)

let directoryId = await GDrive.files.safeCreateFolder({
        name: "myapp",
        parents: ["root"],
});

console.log(await GDrive.files.get(directoryId));

Get Error:
[TypeError: undefined is not an object (evaluating 'Object.keys(queryParams)')]

While using:
const queryParams = {
    fields: "description",
};
console.log(await GDrive.files.getMetadata(fileID, queryParams));

Get Error:
[TypeError: _reactNativeGoogleDriveApiWrapper.default.files.getMetadata is not a function. (In '_reactNativeGoogleDriveApiWrapper.default.files.getMetadata(directoryId)', '_reactNativeGoogleDriveApiWrapper.default.files.getMetadata' is undefined)]

**Comment by RobinBobin** [comment]
Will you see the same issue if you use my example project? The link is in the docs to the library.

**Comment by RobinBobin** [comment]
I'll close, as it's been inactive for a while.
