### ISSUE TITLE
[AbortError: Aborted] while listing files 

### ISSUE THREAD

**Issue by RoshanNepal** [RobinBobin/react-native-google-drive-api-wrapper#67]
I am trying to list files stored in the google drive. Sometimes it works but most of the time I get `[AbortError: Aborted]` error.

`try{`
    `gdrive.accessToken = (await GoogleSignin.getTokens()).accessToken;`
    `let data = await gdrive.files.list({`
       `q: new ListQueryBuilder()`
         ` .e('name', 'fileName')`
         ` .and()`
          `.e('mimeType', 'application/octet-stream'),`
      `});`
`}`
`catch(e){`
      `console.log(e)`
`}`

**Comment by anferrat** [comment]
It's probably time-out for your fetch request. set gdrive.fetchTimeout = -1 for infinite time out. Check docs for more

**Comment by RoshanNepal** [comment]
It works. Thank you
