### ISSUE TITLE
AccessToken Generation Issue

### ISSUE THREAD

**Issue by RenatoBarrosDeLima** [RobinBobin/react-native-google-drive-api-wrapper#7]
Hello Robin, I have a problem that I can not solve. I need to upload files to google drive. I have authenticated with react-native-google-signin.
But how do I get ACCES_TOKEN? I always have this 401 error.

**Comment by wmonecke** [comment]
Hey @RenatoBarrosDeLima!

The Access_token can be found in the response of react-native-google-sign-in.
It has nothing to do with this package.

Try successfully login in via google and console.log() the response. You should see an access-token field with the actual token. You use that token to correctly set up this package.

**Comment by RenatoBarrosDeLima** [comment]
@wmonecke, Thanks for answering. Start here to see if I succeed.

**Comment by RenatoBarrosDeLima** [comment]
Thank you for helping me solve the problem. I was actually able to locate Access_Token in the react-native-google-signin package.

**Comment by MehdiRaza1998** [comment]
Thanks , I finally found it too,   

        const token= (await GoogleSignin.getTokens()).accessToken;
