### ISSUE TITLE
DOMException: Aborted while getting bigger size file from google drive

### ISSUE THREAD

**Issue by NTJ3** [RobinBobin/react-native-google-drive-api-wrapper#71]
@RobinBobin  getting this error while getting binary for bigger file. I'm trying with file size almost 20mb

```
     gdrive.files
      .getBinary(item.id, undefined, '2').then((resGetMetadata) => {
        console.log(resGetMetadata);
      }).catch((err) => {
        console.log(err);
      });

```

**Comment by RobinBobin** [comment]
Getting what error? Copy/Paste the error text.

My wild guess, it's a timeout issue, though. Search for `fetchTimeout` in the docs.

**Comment by ThreeHAN** [comment]
Tyring to set `fetchTimeout`  to 10 seconds to see if that helps.

**Comment by RobinBobin** [comment]
I'll close it, since it's been inactive for a while.
