### ISSUE TITLE
Upload video/mp4

### ISSUE THREAD

**Issue by Nazar1310** [RobinBobin/react-native-google-drive-api-wrapper#72]
I'm trying to load a video in base64 format and I get a file on the disk that doesn't work, but it works great with pictures
```
gdrive.files
  .newMultipartUploader()
  .setData(base64Data, MimeTypes.BINARY)
  .setIsBase64(true)
  .setRequestBody({name})
  .execute();
```
File Info
• Resolution: 720×1280
• Duration: 15.125s
• MIME type: video/mp4
• Extension: mp4
• Size: 1.19 MB

**Comment by RobinBobin** [comment]
How doesn't it work?

**Comment by RobinBobin** [comment]
Will it playback if you download it?

**Comment by RobinBobin** [comment]
Where do you get `base64Data` from?

**Comment by RobinBobin** [comment]
Will anything change if you set its MIME type as `video/mp4`?

**Comment by Nazar1310** [comment]
> 

Yes, it played after booting, it won't open due to processing on the disk, I didn't see that.

Everything works great, thanks for the quick reply, and sorry for my inattention.

**Comment by RobinBobin** [comment]
:slightly_smiling_face: :+1: I'm glad you got it working.

**Comment by RobinBobin** [comment]
I'll close it, since it's been inactive for a while.
