### ISSUE TITLE
Want to create a folder using this GDrive library and Add files to that folder

### ISSUE THREAD

**Issue by mimranzulkfal** [RobinBobin/react-native-google-drive-api-wrapper#74]
Hey @RobinBobin!

I want some help from this team. I want to **create a new folder** in the root directory in my GDrive and **save new files in that folder**. Can you share some code snippets for this purpose? 

I'll be thankful to you :)

**Comment by RobinBobin** [comment]
Please have a look at the sample project linked in the readme.

**Comment by mimranzulkfal** [comment]
@RobinBobin I have gone through that but can't get it specifically for creating a new folder and writing JSON files to that folder. 

Kindly tell me about some code snippets. I'll be thankful to you.

**Comment by RobinBobin** [comment]
https://github.com/RobinBobin/gdrivetest/blob/master/src/Files.tsx

**Comment by mimranzulkfal** [comment]
I'm creating same as it is but it's not creating a folder on my drive. Have a look:
![image](https://user-images.githubusercontent.com/99423116/187802372-0be5f80a-62ee-400e-8a60-fb6254585fed.png)

**Comment by RobinBobin** [comment]
Are you sure you don't have this folder already?

**Comment by RobinBobin** [comment]
Is an exception thrown?

**Comment by mimranzulkfal** [comment]
I have no folder with this name on the drive. Also there is no exception thrown.

**Comment by RobinBobin** [comment]
Try running my project.

Try listing files to make sure you setup everything correctly.

**Comment by mimranzulkfal** [comment]
If I use only this part only then folder is creating fine:

oogleDrive.files.newMetadataOnlyUploader().setRequestBody({
          name: "MyFolder",
          mimeType: MimeTypes.FOLDER,
          parents: ["root"],
        })

But it'l create a new folder with same name everytime.

**Comment by RobinBobin** [comment]
What will happen if you run my project and press the corresponding button?

**Comment by mimranzulkfal** [comment]
Hey Robin!

I have created a folder but now how please check I'm passing folderID right or not? My newly created folder name is condition_folder.

I'm doing in this way but file isn't uploading.

![image](https://user-images.githubusercontent.com/99423116/187899581-2c69d54b-8bc1-441b-8fdd-2fb39cae3fe0.png)

**Comment by RobinBobin** [comment]
Please consult official google drive docs as for `parents`. I think you're setting it wrong.
I'm pretty sure you'll find something interesting in the thrown exception.
Why are you pasting screenshots with your code? Imagine someone wants to copy paste it to run.
