### ISSUE TITLE
Regenerate accessToken using old refreshToken

### ISSUE THREAD

**Issue by mimranzulkfal** [RobinBobin/react-native-google-drive-api-wrapper#77]
Hi @RobinBobin 

I want to regenerate the new accessToken on the basis of the old refreshToken. Is there anything in your mind? Any library or Google Drive API Fetch URL that works for me?

**Comment by RobinBobin** [comment]
Hello,
Sorry, I don't even understand what you're talking about, so there's nothing on my mind.
Anyway, my package is just a wrapper around the GDrive API. Some other package must be used to handle tokens, signing in, etc.
