### ISSUE TITLE
Creating a folder using createIfNotExists(...) throws error EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by affcue25** [RobinBobin/react-native-google-drive-api-wrapper#79]
Hi, I hope you are doing great. 
I have been trying to create/read my files in a specific folder, and for that I am using createIfNotExists(...) function. As par your document this function check if the folder exist then throw the id of that folder other wise create a new folder and throws its id.. 
But I am doing the same code as you have given, but its throwing me exception
 _EISDIR: illegal operation on a directory, read_ 

Heres my code: 

```
console.log("folder object",await invoker(async () => (
      await gdrive.files.createIfNotExists(
        {
          q: new ListQueryBuilder()
            .e("name", "TestFolder")
            .and()
            .e("mimeType", MimeTypes.FOLDER)
            .and()
            .in("root", "parents")
        },
       (await gdrive.files.newMetadataOnlyUploader()
          .setRequestBody({
            name: "TestFolder",
            mimeType: MimeTypes.FOLDER,
            parents: ["root"]
          }).execute()).id
        ).catch(e=> {
          console.log("error folder", e);
        })
    )));
```
    
    Here's my scopes:
    
    `scopes: [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.appdata",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.appfolder",
      'https://www.googleapis.com/auth/drive.metadata',
    ],`

**Comment by affcue25** [comment]
I mean, isnt this function works with query as 1st Param, when query fails to find the folder/file, it execute the 2nd param and returns the result?
So, in my case, I am making a query to find folder by name, if it doesnt exist or query fails, then in my 2nd param I am creating a folder... but if folder already exist then it should throw me any result or ID of that folder... 

```
await gdrive.files.createIfNotExists(
      {
        q: new ListQueryBuilder()
          .e("name", "condition_folder")
          .and()
          .e("mimeType", MimeTypes.FOLDER)
          .and()
          .in("root", "parents")
      },
      await (gdrive.files.newMetadataOnlyUploader().setRequestBody({
        name: 'condition_folder',
        mimeType: MimeTypes.FOLDER,
        parents: ['root'],
      }).execute()
```

**Comment by RobinBobin** [comment]
Hi,
Did you sort it out, or some assistance is still needed?
