### ISSUE TITLE
 Error exporting google drive file

### ISSUE THREAD

**Issue by RenatoBarrosDeLima** [RobinBobin/react-native-google-drive-api-wrapper#8]
Hello, I have a problem when I try to export a file from Google Drive. When I try to export any file I always get this error.

![Console log()](https://user-images.githubusercontent.com/24270730/55883689-23224980-5b7d-11e9-8b84-58573c87a466.png)

This is the function I use for exporting this file.

![Function()](https://user-images.githubusercontent.com/24270730/55883714-30d7cf00-5b7d-11e9-851b-f341bd378c70.png)

This file I created in the API test, and I can not export it myself.

![File create in API test Google](https://user-images.githubusercontent.com/24270730/55883729-39c8a080-5b7d-11e9-8850-bac0215f0226.png)

Google drive API is already enabled. 
I really do not know why I get error 403

**Comment by RobinBobin** [comment]
Hi there!
I think you're getting this error because you're using the wrong function. `GDrive.files.export` is used to export a google document. And you set mime as `application/octet-stream`.

**Comment by RenatoBarrosDeLima** [comment]
Thanks for the tip. Actually I was using the module the wrong way. I've been able to solve the problem, thank you.

**Comment by MehdiRaza1998** [comment]
How did you solve the problem please share it with us.
