### ISSUE TITLE
more than 2 chunks were not able to be uploaded in resumableUploader

### ISSUE THREAD

**Issue by sam-uraii** [RobinBobin/react-native-google-drive-api-wrapper#82]
**Premise**: I was trying to upload a video of 45 MB through resumableUploader with one chunk equals to around 4MB.

**Problem**: After 2 successful uploaded chunks the API was keep failing with error that "uploaded byte offset is 800000 but you are uploading byte offset is 1200000" (the error was not exactly the same but you get the gist right!!).....

**Solution**: in ResumableUploader file in uploadChunk function after the successful upload of the chunk we check that is response.status === 308, if yes then we do::::->
 
```
if (response.status === 308) {
       const transferredByteCount = this.processRange(response);
    

      this.__transferredByteCount += transferredByteCount

      return {
        isComplete: false,
        transferredByteCount,
      }
    }
```

but there is a problem in the above check, this.processRange function return the higher value of the current range uploaded (400000 - 800000) which will be 800000 and we add 800000 with previously __transferredByteCount (last uploaded range offset) which will become 1200000 and when we will go for uploading the next chunk we will start the "to"(start range) from 1200000 instead of 800000 ..............so the API will continue to fail....

> I have raised a PR for this too please do review it

---->
https://github.com/RobinBobin/react-native-google-drive-api-wrapper/pull/81#issue-1380021758

**Comment by RobinBobin** [comment]
Thanks for raising an issue. I'll check.

**Comment by sam-uraii** [comment]
okay.....thanks

**Comment by RobinBobin** [comment]
https://github.com/RobinBobin/react-native-google-drive-api-wrapper/pull/81#issuecomment-1253389448
