### ISSUE TITLE
[TypeError: Network request failed] Randomly

### ISSUE THREAD

**Issue by sam-uraii** [RobinBobin/react-native-google-drive-api-wrapper#84]
Any time I run an upload API whether it is a resumable uploader or multipart uploader **[TypeError: Network request failed]**  <--this error comes.
**How does It occur-->**

**a.)** After uploading 2 - 3 (sometimes 1-2) photos in the multipart uploader it starts giving this error.

**b.)** once the one request in the resumable upload is successful for the second request it shows this error and after retrying 8-9 times it suddenly starts working or sometimes even after 50 retries it doesn't work...

**---->** I was using **version 0.6.0 earlier**, and everything was working fine....the problem started occurring after I **upgraded to 1.2.3**. ResumableUploder is the new thing I added but the code for multipart is as same as it was for the earlier version..... So it seems there has to be something new I may have to add. not sure...**please help...**

**PS: drive.fetchTimeout = 10000;** 

**MY MULTIPART UPLOADER**

```
result = await drive.files
        .newMultipartUploader()
        .setData(fileContent, mimeType)
        .setIsBase64(true)
        .setRequestBody({
          originalFilename: originalFilename,
          name: dataInfo.uri,
          createdTime: dataInfo.createdTime,
          parents: [folderId],
        })
        .execute();
```

**Comment by RobinBobin** [comment]
That's sad. Unfortunately, currently I have no time to tackle it, what makes me even more sad. I do hope you'll manage to sort it out and a PR is certainly always welcome.

**Comment by sam-uraii** [comment]
okay.....sure np.. I'll do whatever I can.

**Comment by sam-uraii** [comment]
Please Help!!! for this issue....this issue still persists and I have big feature to push now......I tried to find out the problem but no luck/........PLEASE HELP!!!

**Comment by RobinBobin** [comment]
Hi!
Can you reproduce the issue in my [sample app](https://github.com/RobinBobin/gdrivetest)?
If so, could you share the file(s) you're having this problem with?

**Comment by sam-uraii** [comment]
yes I took inspiration from your sample just the difference is that I am using javascript....Can specify which file you are asking like the code I wrote or something else??

**Comment by RobinBobin** [comment]
Inspiration is great, but I'm asking if you can reproduce the problem while uploading your files with my sample app.
