### ISSUE TITLE
TypeError: fetch is not a function. (In 'fetch(this.resource, this.init)', 'fetch' is false)

### ISSUE THREAD

**Issue by divyangkhatri** [RobinBobin/react-native-google-drive-api-wrapper#85]
Hello @RobinBobin 
### **System Configuration**
mac-os : 12.3.1
"react-native": "^0.69.4",
"@robinbobin/react-native-google-drive-api-wrapper": "^1.2.3"
iOS version simulator version : 15.5
I am also using rn-nodeify.

### **Error details**
```
TypeError: fetch is not a function. (In 'fetch(this.resource, this.init)', 'fetch' is false)
```
### Step to reproduce

1. Install the app
2. Click on google drive button for list drive file
it will throw mention error.

### How to solve this error

1. Install the app
2. Click on google drive button for list drive file
3. Close the app and re open the app again
4. Click on google drive button for list drive file and now error is gone.

**Comment by RobinBobin** [comment]
Hi @divyangkhatri!
I'm sorry you're having trouble with my lib.
Unfortunately I don't have time to tackle this problem right now... and I don't have a Mac.
I had a similar issue here: https://github.com/RobinBobin/react-native-google-drive-api-wrapper/issues/69
Maybe it could help.

**Comment by divyangkhatri** [comment]
@RobinBobin ,
Not found any solution,
This is only bugs in iOS for android it is working.

**Comment by divyangkhatri** [comment]
I have fixed this issue with.
```
global.fetch = fetch
```
in main index.js file

**Comment by RobinBobin** [comment]
I'm glad you got it working!
