### ISSUE TITLE
How to add fields to file list request

### ISSUE THREAD

**Issue by lykfe** [RobinBobin/react-native-google-drive-api-wrapper#88]
https://developers.google.com/drive/api/guides/fields-parameter

I'm trying to do something like
`files.list(fields='files(id,capabilities,canAddChildren)')`

Is this supported?
If it is, can you provide a simple example that I can work with?

Thanks

**Comment by RobinBobin** [comment]
Have a look at `Files.list` in the readme.

**Comment by lykfe** [comment]
Would highly appreciate if you can update the document to include an example of using field.

**Comment by RobinBobin** [comment]
Glad you have it sorted. Ok, I'll try :slightly_smiling_face: .
