### ISSUE TITLE
Android sign-in required after restarting the app

### ISSUE THREAD

**Issue by wmonecke** [RobinBobin/react-native-google-drive-api-wrapper#9]
Hey Robin! This package has helped me out a lot. Thank you!

I don't know if it is a bug or it's just me who is not doing something right but on Android, I back up a copy of the apps state into GDrive every time the app initializes.

```
async onBackupData() {
    const isUserLoggedIn = await GoogleSignin.isSignedIn();
    console.log('isUserLoggedIn', isUserLoggedIn)
    if (!isUserLoggedIn) return false;

    try {
      const userInfo = await GoogleSignin.signInSilently();
      console.log('userInfo from .signInSilently', userInfo);

      GoogleSignin.clearCachedToken()
      .then(() => {
        
        GoogleSignin.getTokens()
        .then(tokenObject => {
          return this.props.createNewGoogleDriveBackup(tokenObject.accessToken, { ...this.props.appState });
        })
        .catch(err => console.log('error', err));
      })
      .catch(error => console.log('error clearing cached token', error));

    } catch (error) {
      console.log('error', error)
    }
  }
```

1. Sign in into Google.
2. I leave the app and close it.
3. Reopen the app and this method is called in componentDidMount()

I get the following error: SIGN_IN_REQUIRED

This is only happening on Android. 

Am I missing something?

**Comment by RobinBobin** [comment]
Hello Walter!

Thank you, I'm glad my package is useful.

A bit of an offtopic, but this phrase caught my eye: "I back up a copy of the apps state into GDrive every time the app initializes". What if the app state is changed, then the app is exited and then killed? I'm pretty sure the new state will be lost.

Back to your question. You have several `.catch` handlers and a `try/catch` handler. At which step do you get the error?

**Comment by wmonecke** [comment]
What if the app state is changed, then the app is exited and then killed? I'm pretty sure the new state will be lost.

 -> Yes that's true, the app also updates the state on certain critical occasions within the app.

The error I am getting is from the try/catch block. The error is coming from `.getTokens()`. I'm pretty sure because I had it before adding the `.signInSilently()` method.

I'm going to see if it is really it.

**Comment by RobinBobin** [comment]
Ah, I see.

Well, I'm glad you're having some progress. Don't hesitate to ask if I can be of any help.

**Comment by wmonecke** [comment]
Sorry for the confusing answer.

This code works on iOS but not on Android:

```
onBackupData() {
    GoogleSignin.isSignedIn()
    .then(isUserLoggedIn => {
      console.log('isUserLoggedIn', isUserLoggedIn)
      if (!isUserLoggedIn) return false;

      GoogleSignin.signInSilently()
      .then(() => {
        console.log('successful .signInSilently')
        GoogleSignin.clearCachedToken()
        .then(() => {
          console.log('successful .clearedCachedToken')
          setTimeout(() => {
            GoogleSignin.getTokens()
            .then(tokenObject => {
              console.log('successful .getTokens', tokenObject)
              return this.props.createNewGoogleDriveBackup(tokenObject.accessToken, { ...this.props.appState });
            })
            .catch(err => console.log('error gettingTokens', err));
          }, 3000);
        })
        .catch(err => console.log('err clearing cached token', err));
      })
      .catch(err => console.log('error signInSilently', err));
    })
    .catch(err => console.log('user is not logged in', err))
  }
```

on iOS I can login into google then close the app and open the app for it to back up the data. On the other hand in android I get the following error 

`'error signInSilently', { [Error: SIGN_IN_REQUIRED]`

.signInSilently is not working on android somehow :/

**Comment by RobinBobin** [comment]
Hmm...
Can you comment out the lines where you use my module and try again? We'll know then which module is failing. My or GoogleSignIn.

**Comment by wmonecke** [comment]
Woah sorry, I made a very stupid mistake!

I was writing this bug here when this package has nothing to do with signIn.
My bad and thanks again for the great package.

**Comment by RobinBobin** [comment]
:) That's ok. Happy coding.

Thanks, doing my best.
