### ISSUE TITLE
Upload progress callbacks?

### ISSUE THREAD

**Issue by tfsjohan** [RobinBobin/react-native-google-drive-api-wrapper#90]
Is there any way to get the upload progress of a file upload so you could make a progress bar while uploading?

**Comment by RobinBobin** [comment]
Resumable uploads are the way out, I think. четверг, 20 июля 2023г., 18:47 +03:00 от Johan Nordberg  ***@***.*** :

**Comment by RobinBobin** [comment]
I'll close as stale.
