### ISSUE TITLE
Upload SQLite3 db file

### ISSUE THREAD

**Issue by MateoGonzalez22** [RobinBobin/react-native-google-drive-api-wrapper#92]
Hi, im trying to upload a sqlite3 db file as a backup to drive, i tried the example code in the README that uses ```newMultipartUploader()```.   

I tried this:

```
 const databaseFile = await RNFS.readFile(databaseFilePath, 'base64')
            
const res = (await gdrive.files.newMultipartUploader()
    .setData(databaseFile, MimeTypes.BINARY)
    .setRequestBody({
        name: "database.db"
    })
    .execute()
);
```
Reading the db as base64 seems to work right since i tried writing a new db file based on the base64 content and it works fine.

When the database.db is uploaded its in text/plain mimeType and its unreadable for sqlite editors

I also tried ```const newDbContent = await gdrive.files.getBinary(id)``` but writing a file with that content doesnt work

I really dont understand how file encoding types work so i dont know if im missing something.

**Comment by MateoGonzalez22** [comment]
I forget to use .setIsBase64(true), that solved the issue

**Comment by RobinBobin** [comment]
Congrats 🎉 !
