### ISSUE TITLE
Make tsc with strict mode happy

### ISSUE THREAD

**Issue by hongqn** [RobinBobin/react-native-google-drive-api-wrapper#95]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

`tsc` with `strict: true` reports the following error:

```
node_modules/@robinbobin/react-native-google-drive-api-wrapper/api/permissions/Permissions.ts(11,40): error TS2322: Type 'object | undefined' is not assignable to type 'object'.
  Type 'undefined' is not assignable to type 'object'.
node_modules/@robinbobin/react-native-google-drive-api-wrapper/api/permissions/Permissions.ts(17,54): error TS2322: Type 'object | undefined' is not assignable to type 'object'.
  Type 'undefined' is not assignable to type 'object'.
```

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@robinbobin/react-native-google-drive-api-wrapper@1.2.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@robinbobin/react-native-google-drive-api-wrapper/api/aux/Uris.ts b/node_modules/@robinbobin/react-native-google-drive-api-wrapper/api/aux/Uris.ts
index f9fd8d1..936c9c2 100644
--- a/node_modules/@robinbobin/react-native-google-drive-api-wrapper/api/aux/Uris.ts
+++ b/node_modules/@robinbobin/react-native-google-drive-api-wrapper/api/aux/Uris.ts
@@ -15,7 +15,7 @@ interface FilesParameters {
 interface PermissionsParameters {
   fileId: string
   permissionId?: string
-  queryParameters: object
+  queryParameters?: object
 }
 
 interface UriParameters {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by RobinBobin** [comment]
Hello there,
Thanks a lot for the message and the patch. Could you make another step forward in improving my package and making a PR from your patch, please? I will gladly merge it.
Thanks.

**Comment by RobinBobin** [comment]
Please, increase the version to `1.2.4` if you make a PR 🙏 .

**Comment by hongqn** [comment]
Thanks for the quick response.  I'll submit a PR :)
