### ISSUE TITLE
Video in gdrive not playing after upgrading React Native version

### ISSUE THREAD

**Issue by MobolajiRichard** [RobinBobin/react-native-google-drive-api-wrapper#98]
Hi @RobinBobin , Thanks for this library, 

I have been using this library to upload videos to gdrive using the code snippet below in my RN codebase v0.64 and everything works fine, however after upgrading the project to v0.73, the video gets uploaded successfully to gdrive but shows the error this "video cannot be played" and when i try to download the video, it opens but shows this very long duration as shown below whereas the video uploaded is just 15seconds long.

<img width="343" alt="Screen Shot 2024-02-04 at 6 31 48 AM" src="https://github.com/RobinBobin/react-native-google-drive-api-wrapper/assets/104364699/2e550bb5-3553-4fd5-9fc4-083ec42e7ad8">

What do you think is causing this issue and how can i go about this,  i'm currently stuck.

const response = await gdrive.files
      .newMultipartUploader()
      .setData(content, 'video/mp4')
      .setIsBase64(true)
      .setRequestBody({
        name: inputText,
      })
      .execute().catch(err => {
        this.setState({isUploading:false});
        Alert.alert(
          'Error Uploading video',
          "Please ensure you're signed in!",
          [
            {
              text: 'OK',
              style: 'cancel', // You can change 'cancel' to 'destructive' for a red button
            },
          ],
        );
        console.log(err);
      });

I have also tried using resumable uploader like below , still getting the same issue

    const binaryData = Buffer.from(content, 'base64');

    const byteArray = Array.from(binaryData);

    const uploader = gdrive.files
      .newResumableUploader()
      .setData(byteArray, MimeTypes.BINARY)
      .setRequestBody({
        name: inputText,
      });

    const response = await uploader.execute().catch(err => {
      this.setState({isUploading: false});
      Alert.alert('Error Uploading video', "Please ensure you're signed in!", [
        {
          text: 'OK',
          style: 'cancel', 
        },
      ]);
      console.log(err);
    });

React Native: v0.73
@robinbobin/react-native-google-drive-api-wrapper : v1.2.3

**Comment by RobinBobin** [comment]
Hi @MobolajiRichard ,
Got it, will try to do something about it.
Sorry for the trouble.

**Comment by RobinBobin** [comment]
Could you show how you read the video file contents before uploading to g-drive, please?

Currently it's the only wise phrase that comes to my mind, unfortunately 🫤.

**Comment by RobinBobin** [comment]
Could you show how you read the video file contents before uploading to g-drive, please?

Currently it's the only wise phrase that comes to my mind, unfortunately 🫤.

**Comment by RobinBobin** [comment]
Why are you using base64 and not uploading the file as binary, please?

**Comment by MobolajiRichard** [comment]
> Could you show how you read the video file contents before uploading to g-drive, please?
> 
> Currently it's the only wise phrase that comes to my mind, unfortunately 🫤.

I'm reading the file content using the rn-fetch-blob package. 
The uri is gotten after recording using the RNCamera 

const content = await RNFetchBlob.fs.readFile(uri, 'base64');

**Comment by MobolajiRichard** [comment]
> Why are you using base64 and not uploading the file as binary, please?

the base64 seemed to be working before the upgrade. But after the upgrade i tried uploading as a binary using the code snippet below, the same error still occured.

const content = await RNFetchBlob.fs.readFile(uri, 'base64');
const binaryData = Buffer.from(content, 'base64');
const byteArray = Array.from(binaryData);

const uploader = gdrive.files
  .newResumableUploader()
  .setData(byteArray, MimeTypes.BINARY)
  .setRequestBody({
    name: inputText,
  });

const response = await uploader.execute().catch(err => {
  this.setState({isUploading: false});
  Alert.alert('Error Uploading video', "Please ensure you're signed in!", [
    {
      text: 'OK',
      style: 'cancel', 
    },
  ]);
  console.log(err);
});

**Comment by RobinBobin** [comment]
Sorry, I didn't make myself clear enough. 
What will happen if you replace `base64` with `utf` in  `RNFetchBlob.fs.readFile(uri, 'base64');`? Will it give you a byte array?

**Comment by MobolajiRichard** [comment]
Hey @RobinBobin, Apologies debugging further I saw that the issues wasn't coming from your library but from the react-native-camera package I'm using to record the video.... But anyways thanks for your help

**Comment by RobinBobin** [comment]
Got it. I wish you all the success 👍
