### ISSUE TITLE
Is there any way to get date of the uploaded file?

### ISSUE THREAD

**Issue by inthisar-hamza** [RobinBobin/react-native-google-drive-api-wrapper#99]
Everthings works well, but there is no way to find the date of updated or uploaded files, Date required in most of the usecases to let the user's know last updated date time, is there are possible way to implement it? or through another API call or something?

I found that there is getMetadata method, but am I need to get `https://www.googleapis.com/auth/drive.metadata.readonly` permission for that?

thanks for the work anyway!

**Comment by RobinBobin** [comment]
Hi,
Please, have a look at the google drive api docs. My library is just a wrapper around it.
